cursor.py
=> Fix error handling type lookup for cursor.

ssl_wrap_socket.py
=> Remove redef of settimeout in ssl code.

test/test_put_get_medium.py
disabling ORC tests as the feature is not enabled in production.
=> disabled ORC test case until the server enables it

ocsp_pyopenssl.py, setup.py, test/test_ocsp.py
@csande and @blr246, can you please review the change for issue #13 ?
The internal test passed. Will check TravisCI test for this PR.
=> SNOW-31353: relaxed dependent component versions

setup.py
Adjusted boto3, pyopenssl and cryptography
=> adjusted boto3, pyopenssl and cryptography

setup.py
=> fix pyasn1, pyasn1-modules versions

azure_util.py, constants.py, file_transfer_agent.py, remote_storage_util.py, s3_util.py, setup.py, test/test_put_get_with_azure_token.py
- Added Azure support for PUT and GET commands
- Updated `cryptography`, `boto3` and `botocore` version requirements
=> SNOW-34176: Azure support

DESCRIPTION.rst, ocsp_pyopenssl.py, version.py
- Improved OCSP response cache util
- Bumping up version to 1.4.14
=> Catchup for 1.4.14

DESCRIPTION.rst, network.py, ocsp_asn1crypto.py, version.py
=> Prep 1.5.1

file_transfer_agent.py
=> Fixed Issue/PR #75: TypeError: list indices must be integers or slices, not str

test/test_concurrent_insert.py
As DML concurrency support is being improved by the server, the test was updated.
=> updated concurrent insert test

s3_util.py, ssl_wrap_socket.py, test/test_unit_s3_util.py
Retry OpenSSL.SysCallError errors. This is to improve the tests.
=> retry raw OpenSSL connection transient errors

test/test_connection.py
@ankit-bhatnagar167 This is a hot patch. See SNOW-83424 for details.
=> SNOW-83424: disabled test temporarily

.github/workflows/jira_comment.yml, .github/workflows/jira_issue.yml
Move new jiras to Data Platoform
=> Suppress failures if no jira can be identified

cpp/ArrowIterator/CArrowChunkIterator.cpp, cpp/ArrowIterator/CArrowChunkIterator.hpp, json_result.py
Syncing this to public repo before release
=> SNOW-167749 fixed DictCursor memory leak issue

cursor.py, test/pandas/test_arrow_pandas.py
=> Sync 30072020

file_transfer_agent.py
Please see ticket for description!
=> SNOW-182731 fix put issue

util_text.py
I somehow must have skipped this change when I was syncing sometime before.
This should be the last sync from the monorepo. I manually checked this time
=> SNOW-150710 fixing sync issue

MANIFEST.in
MANIFEST.in needed to updated when I added the `src` folder.
Sorry, I didn't know what this file was for before.
=> SNOW-184252 update MANIFEST.in

.github/workflows/build_test.yml, .pre-commit-config.yaml, test/extras/README.rst, test/extras/no_use_pycon.py, test/extras/run.py, tox.ini
Adding new set of tests to test some special cases with the connector.
This in specific is to catch the issue that caused 2.3.1 release.
Tests #377
=> RETRO-246 adding extras tests

test/README.rst, tested_requirements/README.rst, tested_requirements/requirements_35.txt, tested_requirements/requirements_36.txt, tested_requirements/requirements_37.txt, tested_requirements/requirements_38.txt
manually syncing newest requirements files for release
=> manually syncing requirements files

src/snowflake/connector/file_util.py
=> SNOW-189907 use context manager for opening a file

DESCRIPTION.rst, src/snowflake/connector/version.py
Bump up Python Connector Version to 2.3.2
=> Bump up Python Connector Version to 2.3.2

src/snowflake/connector/connection.py, src/snowflake/connector/util_text.py, test/test_cursor.py, test/test_execute_multi_statements.py
SNOW-172631
Filtering out empty statements from `execute_stream` and `execute_string`.
=> SNOW-172631 filter empty lines out of execute_string and execute_stream

.github/actions/gajira-create/action.js, .github/actions/gajira-create/action.yml
Adding extra debugging to jira create action
=> SNOW-197364 add extra debugging

test/pandas/test_unit_options.py
We merged a PR that was not rebased onto master.
=> SNOW-194973 added missing header

.github/dependabot.yml
SNOW-200259
dependabot meet snowflake-connector-python
=> SNOW-200259 dependabot

src/snowflake/connector/ocsp_snowflake.py, test/test_ocsp.py
From #413 
This fixes the most often failing flaky tests
It mostly just adds more logging and fixes the tests for the OCSP cache the right way.
=> SNOW-164802 resolve OCSP flakiness and add more logging

src/snowflake/connector/secret_detector.py, src/snowflake/connector/telemetry.py, test/test_unit_log_secret_detector.py
Fixed SecretDetector Bug for None String. Also got secret detector to 100% code cov
=> Fixed SecretDetector Bug for None String

.github/workflows/build_test.yml, tox.ini
Added code coverage HTML output to be a github artifact so that developers can view their own code coverage stats
=> Added code coverage HTML output to be a github artifact

.github/workflows/build_test.yml, tox.ini
I tried changing some of our `tox` configuration to allow me locally to run a single test easily.
However, I forgot that we do something a little different in Jenkins that would break with that change, here in this PR I revert the part of that change that is causing the Jenkins failures, I will give more thought to how to properly resolve this in the future.
Sorry for the failures!
=> SNOW-201468 fix test names

DESCRIPTION.rst
Did some modification to release notes as per suggested by Docs Team
=> Modified Release Notes as per Docs Team Suggestion

Jenkinsfile
After this change the PR's will be visible here  https://ci44.int.snowflakecomputing.com/view/GithubFolders/job/PyConnector/job/snowflake-connector-python/view/change-requests/ and the check will also come in `All checks have passed` area beelow
=> Added Jenkinsfile to run Github PR builder

.github/workflows/build_test.yml, src/snowflake/connector/file_transfer_agent.py, test/test_put_get_medium.py, test/test_put_get_with_aws_token.py, test/test_put_get_with_azure_token.py
Added type hints for the progress updating code in file transfer as well as adding test coverage for that code as well
=> SNOW-200123: Added more test coverage for file_transfer_agent

.github/workflows/jira_comment.yml
Changed to what payload looks like in documentation:
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#issue_comment
=> SNOW-210112 fix variable to new GH action payload standard

ci/test.sh, ci/test_fips_docker.sh, tox.ini
This PR fixes the rest of the issues with the FIPS tests that run on Jenkins.
=> SNOW-210833 fix fips jenkins tests

test/integ/conftest.py, test/integ/test_incident.py, tox.ini
This disables currently failing Jenkins tests
=> SNOW-164802 disabled the currently failing Jenkins tests

.github/workflows/build_test.yml, test/integ/test_dataintegrity.py, test/integ/test_put_get.py, test/integ/test_put_get_medium.py, test/integ/test_put_get_user_stage.py, test/integ/test_put_get_with_aws_token.py, test/integ/test_put_get_with_azure_token.py, test/integ/test_put_get_with_gcp_account.py, test/randomize.py, test/unit/test_gcs_util.py, test/unit/test_ocsp.py, tox.ini
SNOW-198369
TL;DR
100% GCS util coverage, 79% overall coverage, ~40% faster tests
=> SNOW-198369 increase GCP put/get code coverage

setup.py
=> SNOW-220160 bump supported pandas version

.github/workflows/build_test.yml
=> SNOW-215838 enable codecov.io uploads

test/unit/test_s3_util.py
SNOW-200122
TL;DR 95.42% s3_util coverage and 79.90% overall code coverage
=> SNOW-200122 increased s3_util coverage

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
SNOW-216517
Improving `cursor.py` code coverage
=> SNOW-216517 improved cursor.py code coverage

src/snowflake/connector/connection.py, src/snowflake/connector/converter.py, src/snowflake/connector/cursor.py, src/snowflake/connector/file_transfer_agent.py, test/integ/conftest.py, test/integ/test_connection.py, test/integ/test_put_get_medium.py, test/integ/test_put_get_with_azure_token.py, test/integ/test_put_get_with_gcp_account.py
Raises `connection.py` code coverage to ~95%
=> SNOW-219413 improve connection cov

.github/workflows/build_test.yml, ci/wss.sh
SNOW-223314
This PR adds back WhiteSource script running to GH actions.
=> SNOW-223314 added WhiteSource script running job to Build and Test

.github/workflows/build_test.yml, README.rst, ci/build_darwin.sh, ci/build_linux.sh, ci/build_windows.bat, ci/test_darwin.sh, ci/test_linux.sh, setup.py, src/snowflake/connector/azure_util.py, src/snowflake/connector/compat.py, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, src/snowflake/connector/pandas_tools.py, tox.ini
SNOW-161047
This PR removes support for Python 3.5 on all platforms and removes the compatibility code necessary for it.
=> SNOW-161047 drop Python 3.5 support

src/snowflake/connector/compat.py, src/snowflake/connector/connection.py, src/snowflake/connector/constants.py, src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, test/integ/test_async.py, test/integ/test_connection.py, test/unit/test_connection.py
SNOW-80651
Adding Async query execution to the Python Connector.
Adds ability to retrieve data for at most day old queries.
=> SNOW-80651 fire and forget/async query execution

setup.py
Bumping `cffi` to next major release.
=> SNOW-223043 bump cffi to next major

setup.py
Bumping `boto3` until next major release.
=> SNOW-223042 bump boto3 to next major

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-236836: Bumped up PythonConnector PATCH version from 2.3.6 to 2.3.7

src/snowflake/connector/azure_util.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_util.py, src/snowflake/connector/s3_util.py, test/conftest.py, test/integ/pandas/test_logging.py, test/integ/pandas/test_unit_options.py, test/integ/test_bindings.py, test/integ/test_concurrent_insert.py, test/integ/test_connection.py, test/integ/test_cursor.py, test/unit/test_gcs_util.py, test/unit/test_ocsp.py, test/unit/test_retry_network.py, test/unit/test_s3_util.py, tox.ini
This PR standardizes how logs are collected, INFO and above in py.test outputs and DEBUG and above into `snowflake_ssm_rt.log` when running tests.
=> SNOW-226899 removed some logging messages

.github/workflows/jira_close.yml
SNOW-242502
Hopefully this works, but there's no way to know before merging
=> SNOW-242502 close Jiras upon closure of their GH issue

.github/workflows/jira_close.yml
=> SNOW-242502 use transitionId instead of transition

.github/workflows/jira_close.yml
=> SNOW-242502 Adding missing checkout

.github/workflows/build_test.yml, src/snowflake/connector/cursor.py, test/integ/test_async.py, test/integ/test_connection.py, test/unit/test_converter.py, tox.ini
SNOW-241508
This PR tries to stabilize our code coverage, so that code parts that seem to be randomly executed sometimes are actually tested and the code coverage does not fluctuate around anymore.
=> SNOW-241508 stabilizing codecov

setup.py, src/snowflake/connector/ocsp_snowflake.py, src/snowflake/connector/ssl_wrap_socket.py, src/snowflake/connector/vendored/urllib3/contrib/_securetransport/bindings.py, test/extras/no_use_pycon.py, test/integ/test_connection.py, test/integ/test_put_get_with_gcp_account.py, test/unit/test_gcs_util.py, test/unit/test_retry_network.py, tox.ini
=> SNOW-257201 Test PR 591

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-258464: Bumped up PythonConnector PATCH version from 2.3.7 to 2.3.8

.github/actions/.gitignore, .github/actions/README.md, .github/actions/gajira-close/README.md, .github/actions/gajira-close/common/net/Jira.js, .github/actions/gajira-close/common/net/client.js, .github/actions/gajira-close/index.js, .github/actions/gajira-close/package-lock.json, .github/actions/gajira-close/package.json, .github/actions/gajira-create/package-lock.json, .github/actions/gajira-create/package.json, .gitignore, test/.gitignore
I was going to add documentation on how to build the connector in the most up to date way as per @sfc-gh-hchaturvedi s request, but I found that I wrote a fairly good one already at: https://github.com/snowflakedb/snowflake-connector-python/blob/master/test/README.rst
But then I found that out custom GH actions are not documented at all, so I checked in those files and wrote a small tutorial on how to compile them again if need be.
I've also updated some gitignores to allow for multiple venvs and parameter files. This is something that I started doing and would like to have these extra files not show up in my `git status`s from now on.
=> SNOW-257781 adding more documentation and files necessary to build custom GH actions

.github/CODEOWNERS
=> SNOW-265864 adding CODEOWNERS

.github/CODEOWNERS
SNOW-265864
Adding a second code owner
=> SNOW-265864 updating CODEOWNERS

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-272313: Bumped up PythonConnector PATCH version from 2.3.8 to 2.3.9

src/snowflake/connector/connection.py, src/snowflake/connector/network.py, test/integ/lambda/test_basic_query.py, test/integ/test_reuse_cursor.py
SNOW-269926
Fixing hanging requests
=> SNOW-269926-fix-timeout-issue

ci/test_linux.sh, test/integ/test_key_pair_authentication.py, tox.ini
SNOW-267170
This PR aims to fix pr-head by fixing a newly discovered bug with our Jenkins test running script and by marking 2 new tests that fail our old driver tests to be skipped when running old driver tests.
I also have a confession to make. I made a mistake of pushing these 2 commits straight into `master` (I forgot to switch branches) at first. After reverting my commits https://github.com/snowflakedb/snowflake-connector-python/commit/f2f73de9bfac4c26b3951e9f59ae2aab28dde334 and https://github.com/snowflakedb/snowflake-connector-python/commit/68c595310b515caaedf0fa82e8c46783da100a0d I have now updated our GitHub settings so that no one will be able to push straight into `master`, I'm sorry!
=> SNOW-267170 fix pr-head and test running script bug

DESCRIPTION.rst, setup.py, src/snowflake/connector/version.py
…… (#617)
* SNOW-274789: Bumped up PythonConnector PATCH version from 2.3.9 to 2.3.10
=> SNOW-274789: Bumped up PythonConnector PATCH version from 2.3.9 to 2.3.10

setup.py, src/snowflake/connector/arrow_iterator.pyx
=> SNOW-200637 ease building conda packages

test/integ/test_put_get.py
SNOW-136583
When I worked on #627 I forgot to add a new test that actually tests that the `threshold` value is being picked up by the connector. I correct my wrongdoing in this PR.
=> SNOW-136583 add a test for threshold number parsing

src/snowflake/connector/json_result.py
For more info see: SNOW-294263
=> SNOW-294263 logging update

src/snowflake/connector/azure_util.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_util.py, src/snowflake/connector/local_util.py, src/snowflake/connector/remote_storage_util.py, src/snowflake/connector/s3_util.py, test/integ/test_put_get.py, test/unit/test_s3_util.py
=> SNOW-216307 Thread safety for parallel upload

test/integ/test_async.py
As I describe in the test's comment:
```
This test tends to hang longer than expected when the testing warehouse is overloaded.
Manually looking at query history reveals that when a full GH actions + Jenkins test load hits one warehouse
it can be queued for 15 seconds, so for now we wait 5 seconds before checking and then we give it another 25
seconds to finish.
```
=> SNOW-298604 making a flaky test more resilient

.github/workflows/build_test.yml, ci/test_linux.sh, tox.ini
By only allowing parallel run in GH actions configuration.
=> Disable unit test parallel execution for Jenkins

src/snowflake/connector/connection.py, src/snowflake/connector/constants.py, test/unit/test_connection.py
Fixes https://github.com/snowflakedb/snowflake-connector-python/issues/665
=> SNOW-329431 Use `QUEUED_REPARING_WAREHOUSE` instead of `QUEUED_REPAIRING_WAREHOUSE`

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-331001: Bumped up PythonConnector PATCH version from 2.4.1 to 2.4.2

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-349164: Bumped up PythonConnector PATCH version from 2.4.2 to 2.4.3

.pre-commit-config.yaml, test/integ/test_async.py
SNOW-354887
Updating pre-commit hooks and fixing one new linting issue
=> SNOW-354887 pre-commit autoupdate

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
SNOW-358757
This PR adds automating labeling of different types of issues. This will help us differentiate them easier in the Issues tab and will be used in the future for automation purposes.
=> SNOW-358757 Update issue templates with tags

.github/ISSUE_TEMPLATE/BUG_REPORT.md
SNOW-358757
Fixing according to example from: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository
=> SNOW-358757 fix multiple labels

.github/ISSUE_TEMPLATE/BUG_REPORT.md
SNOW-358757
Decided to use space instead of underscore once I took a look at historical labels.
=>  SNOW-358757 Update BUG_REPORT.md

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-362269: Bumped up PythonConnector PATCH version from 2.4.3 to 2.4.4

src/snowflake/connector/cpp/ArrowIterator/Python/Common.hpp, src/snowflake/connector/cpp/ArrowIterator/Python/Helpers.hpp
SNOW-364955
1. Fix a potential bug in RAII class, which doesn't correctly release the original object.
2. Clean some code.
=> SNOW-364955: bug fix in pyobject raii class

src/snowflake/connector/connection.py, test/integ/test_session_parameters.py
Re adding the client session keep alive fix in time for behavior change release.
Original PR: https://github.com/snowflakedb/snowflake-connector-python/pull/634
Original PR revert: https://github.com/snowflakedb/snowflake-connector-python/pull/664
=> SNOW-264606 client session keep alive fix added back

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-368557: Bumped up PythonConnector PATCH version from 2.4.4 to 2.4.5

test/integ/test_key_pair_authentication.py
Removing test - will create confluence link instead
=> SNOW-365900 Remove manual test for JWT token validity

pyproject.toml, setup.py
This reverts commit c3bbcb595cec630f0692b01dad3cfc38dd7e30a7.
=> Revert "Update pyarrow requirement from <3.1.0,>=3.0.0 to >=3.0.0,<4.1.0

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-371138: Bumped up PythonConnector PATCH version from 2.4.5 to 2.4.6

test/integ/pandas/test_arrow_pandas.py
This PR address changes requested in [SNOW-370785](https://snowflakecomputing.atlassian.net/browse/SNOW-370785)
It tests that `fetch_arrow_all` and `fetch_arrow_batches` behave correctly with empty queries.
It also cleans up some old code to be a little simpler.
=> SNOW 370785 Add Fetch Arrow Tests

setup.py, test/integ/test_put_get.py
SNOW-371846
Successful run: https://jenkins.int.snowflakecomputing.com/view/ClientMasterJobs/job/RT-PyConnector37-OldDriver/5965/
Small housekeeping item with a previously missing test marker
=> SNOW-371846 mark test_put_threshold as skipolddriver

src/snowflake/connector/result_batch.py, src/snowflake/connector/result_set.py, test/integ/test_cursor.py
This PR begins to address performance issues investigated in: [SNOW-361211](https://snowflakecomputing.atlassian.net/browse/SNOW-361211)
Specifically, it updates the existing fetching logic to leverage all 4 threads of the ThreadPoolExecutor at all times.
This PR also adds debug logs for improved logging/debugging purposes.
=> SNOW-361211 Adds Updated Fetching Logic

DESCRIPTION.rst, src/snowflake/connector/version.py
Co-authored-by: Jenkins User <snowflake-provisioner>
=> SNOW-394801: Bumped up PythonConnector MINOR version from 2.4.6 to 2.5.0

src/snowflake/connector/azure_util.py, src/snowflake/connector/connection.py, src/snowflake/connector/constants.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_util.py, src/snowflake/connector/local_util.py, src/snowflake/connector/remote_storage_util.py, src/snowflake/connector/s3_util.py
SNOW-371967
Adding option to set connection pool size for `boto3`.
Note: this feature is going away soon, so it'll stay undocumented until then
=> SNOW-371967 Added _s3_connection_pool_size setting to SnowflakeConnection

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-407582: Bumped up PythonConnector PATCH version from 2.5.0 to 2.5.1

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
SNOW-405608
This PR adds a PR template
=> SNOW-405608 Create pull_request_template.md

.github/workflows/build_test.yml
1. What GitHub issue is this PR adressing? Make sure that there is an accompanying issue to your PR.
Fixes SNOW-373479
As part of this Jira I previously set the traceback of pytest printing to be less verbose, I unfortunately didn't apply this to all pytest runs.
Here I fix my mistake
=> SNOW-373479 adding more short tracebacks

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Fixes SNOW-417287
This PR fixes some typos in  our PR template and adds an urgent assistance disclaimer to our bug issue template.
=> SNOW-417287 updating PR and issue templates

pyproject.toml, setup.py
=> SNOW-414668 bumping pyarrow to 5 from 3

src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, src/snowflake/connector/result_set.py, test/integ/test_cursor.py
Fixes [SNOW-421184](https://snowflakecomputing.atlassian.net/browse/SNOW-421184)
Ensures tests are passing and fixes error message logging.
=> SNOW-421184 Parallel Fetch Clean Up

.github/workflows/jira_issue.yml
Fixes #[422709](https://snowflakecomputing.atlassian.net/browse/SNOW-422709) 
Changes the github create workflow to use gajira-create from atlassian.
=> SNOW-422709 Use gajira-create from Atlassian

.github/workflows/jira_issue.yml
Fixes #[422709](https://snowflakecomputing.atlassian.net/browse/SNOW-422709) 
Fixes the assignee id and changes the gajira version used.
=> SNOW-422709 Use `gajira-create` from atlassian

test/unit/test_bind_upload_agent.py, test/unit/test_cursor.py, test/unit/test_gcs_client.py, test/unit/test_session_manager.py
Necessary test update related to SNOW-300951
There was a test issue between #725 and #800 this PR fixes that issue.
=> SNOW-300951 updating GCP unit test

.github/workflows/create_req_files.yml
=> SNOW-374125 Add new workflow for automatically publishing requirements files

.github/workflows/build_test.yml, .github/workflows/create_req_files.yml
Fixes SNOW-374125
Just updating some GitHub action steps
=> SNOW-374125 simplifying some steps

src/snowflake/connector/s3_storage_client.py, src/snowflake/connector/storage_client.py, test/unit/test_s3_util.py
Fixes SNOW-443844
Right now with the new PUT/GET implementation these actions are inaccessible on `eufrankfurt`. This is because we were using a legacy signing procedure which is not supported on this S3 deployment.
In this PR I implement the newest signature procedure. See documentation here for implementation details: https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
=> SNOW-443844 Implement AWS signature V4

setup.py
=> SNOW-454169 Bump pandas version to <1.4

src/snowflake/connector/cpp/ArrowIterator/CArrowIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/DecimalConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/IColumnConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/Python/Common.hpp, src/snowflake/connector/cpp/ArrowIterator/Python/Helpers.cpp, src/snowflake/connector/cpp/ArrowIterator/Util/time.hpp, test/integ/pandas/test_arrow_pandas.py, test/integ/pandas/test_unit_arrow_chunk_iterator.py, test/integ/test_arrow_result.py, test/integ/test_put_get.py
Fixes SNOW-357290
Fixing Python deprecation warnings, for examples see: https://github.com/snowflakedb/snowflake-connector-python/runs/3551044708?check_suite_focus=true
=> SNOW-357290 fix deprecation warnings

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-458002: Bumped up PythonConnector PATCH version from 2.6.0 to 2.6.1

src/snowflake/connector/bind_upload_agent.py
Fixes SNOW-448675
Nullifies error thrown when a stage with the same name is attempted to be created in the bulk array bind process.
=> SNOW-448675 Add Create or Replace Stmt

src/snowflake/connector/auth_webbrowser.py
https://github.com/snowflakedb/snowflake-connector-python/issues/303
=> SNOW-157438 Print SSO URL Upon Failure

setup.py, src/snowflake/connector/vendored/requests/__init__.py, src/snowflake/connector/vendored/requests/__version__.py, src/snowflake/connector/vendored/requests/api.py, src/snowflake/connector/vendored/requests/compat.py, src/snowflake/connector/vendored/requests/exceptions.py, src/snowflake/connector/vendored/requests/help.py, src/snowflake/connector/vendored/requests/models.py, src/snowflake/connector/vendored/requests/sessions.py, src/snowflake/connector/vendored/requests/utils.py, src/snowflake/connector/vendored/urllib3/_version.py, src/snowflake/connector/vendored/urllib3/connection.py, src/snowflake/connector/vendored/urllib3/connectionpool.py, src/snowflake/connector/vendored/urllib3/contrib/appengine.py, src/snowflake/connector/vendored/urllib3/contrib/ntlmpool.py, src/snowflake/connector/vendored/urllib3/contrib/socks.py, src/snowflake/connector/vendored/urllib3/packages/six.py, src/snowflake/connector/vendored/urllib3/util/retry.py, src/snowflake/connector/vendored/urllib3/util/ssl_.py
Fixes SNOW-189901
Just updating our vendored dependencies to the newest versions available.
=> SNOW-189901 updating vendored libraries

Jenkinsfile
Fixes PRODSEC-1014
prevent breaking jenkins flow while still reporting appropriate status check
=> PRODSEC-1014 remove throw error

src/snowflake/connector/cpp/ArrowIterator/BinaryConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/BinaryConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/BooleanConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/BooleanConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/CArrowIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/DateConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/DateConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/DecimalConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/DecimalConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/FloatConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/FloatConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/IntConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/Python/Helpers.cpp, src/snowflake/connector/cpp/ArrowIterator/Python/Helpers.hpp, src/snowflake/connector/cpp/ArrowIterator/StringConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/StringConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/TimeConverter.hpp, src/snowflake/connector/cpp/ArrowIterator/TimeStampConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/TimeStampConverter.hpp
Fixes #406 
Hello Snowflake team!  I have been looking for a way to contribute back to the community and I saw @sfc-gh-mkeller tagged this as a good first issue.  I have run the cpplint command and fixed all of the C++ files so that they include the standard C++ header files that they utilize instead of relying on a transitive include which may break in the future.  
Please let me know what else I can do to help this merge!
\~- Chuck -\~
=> SNOW-196953: Include Standard C++ headers

src/snowflake/connector/connection.py, test/unit/test_connection.py
Fixes #SNOW-494740
Adds blocked as a running query, in parallel with JDBC.
=> SNOW-494740 Add Blocked as a Running Query

setup.py
No issue, or Jira
This PR automates package discovery. Having explicit packages is great because it's verbose, but when new people get brought onto the project they always seem confused because new sub packages don't get picked up automatically.
I manually verified that this produces the same packages as the hard-coded list.
=> automate package discovery

setup.py
Reverts snowflakedb/snowflake-connector-python#906
=> SNOW-487250 Revert "SNOW-487250 remove D_GLIBCXX_USE_CXX11_ABI"

.github/workflows/jira_issue.yml
Fixes SNOW-499170
Attempting to fix our JIRA creation GH action
=> SNOW-499170 updating JIRA creation

.github/workflows/create_req_files.yml
Fixes #896 and SNOW-477347
This updates our `.reqs` files in https://github.com/snowflakedb/snowflake-connector-python/tree/master/tested_requirements to include the version of `snowflake-connector-python` instead of having this information as a comment.
=> SNOW-477347 make snowflake-connector-python part of the requirements files

.github/workflows/jira_issue.yml
Fixes SNOW-499170
Fixing a bug I made yesterday
=> SNOW-499170 fix a bug with jira creation

.github/workflows/build_test.yml, Jenkinsfile, ci/build_darwin.sh, ci/build_linux.sh, ci/build_windows.bat, ci/docker/connector_test_fips/Dockerfile
Fixes SNOW-496973
This PR is just updating how we build wheels and source distribution on Jenkins. On GH actions we have already switched to using `build`.
=> SNOW-496973 updating Jenkins builds

src/snowflake/connector/auth_by_plugin.py, src/snowflake/connector/auth_default.py, src/snowflake/connector/auth_idtoken.py, src/snowflake/connector/auth_keypair.py, src/snowflake/connector/auth_oauth.py, src/snowflake/connector/auth_okta.py, src/snowflake/connector/auth_usrpwdmfa.py, src/snowflake/connector/auth_webbrowser.py, test/unit/test_retry_network.py
Fixes a bug introduced in #919 
Ever since we merged #919 tests have been timing out both on Jenkins and GH actions.
=> SNOW-372033 hotfix

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes #936
Should be straightforward.
=> SNOW-499495 Add Cursor.query attribute for accessing last query

src/snowflake/connector/dbapi.py, test/unit/test_dbapi.py
Fixes #907
I think it's self-explanatory.
=> SNOW-487268 make dbapi.Binary bytes not str

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-502072: Bumped up PythonConnector PATCH version from 2.7.0 to 2.7.1

.github/workflows/jira_close.yml, .github/workflows/jira_issue.yml
=> SNOW-421731 use central copy of actions

pyproject.toml, setup.py
Fixes #958  SNOW-500750
Bumping pyarrow
=> SNOW-500750 bump pyarrow to 6.0.0

setup.py
=> bump keyring

setup.py
=> bump numpy

setup.py
=> bump pyopenssl

setup.py
=> bump cryptography

src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, src/snowflake/connector/telemetry.py, test/integ/test_cursor.py, test/integ/test_errors.py, test/integ/test_large_result_set.py
Fixes SNOW-489676
Adds "source" field to other telemetry field for parity with other connectors.
=> SNOW-489676 Add Source Field to Telemetry

test/integ/test_cursor.py, test/integ/test_large_result_set.py
Fixes SNOW-489676
Adding test tags missing form #967
=> SNOW-489676 hotfix test tags

src/snowflake/connector/file_transfer_agent.py
Fixes SNOW-460812
This is a small change that was requested, these error messages point out that some errors could be caused by the connection to blob storage providers.
=> SNOW-460812 better PUT/GET error messages

DESCRIPTION.rst
Fixes #NNNN
We need to keep this file, because we link to it from our DOCS, until that link gets updated we'll keep both
=> reverted DESCRIPTION.rst change

src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, test/integ/test_cursor.py
=> SNOW-501058 Made Cursor.execute() interpolate SQL when params=()

MANIFEST.in, setup.py
Fixes #991 
Adding `py.typed` file to our modules indicates that we have some type-hints in our module for type checkers.
=> SNOW-510552 adding py.typed to snowflake-connector-python

src/snowflake/connector/connection.py
Fixes #987 
With recent changes `BLOCKED` is considered to be still running, because of this it should not be considered to be an error anymore.
=> SNOW-507674 don't consider BLOCKED to be an error

src/snowflake/connector/connection.py, test/integ/test_cursor.py
Fixes SNOW-491028
The rest object (status_resp["data"]) turns out to be missing the "queries" field if there's a network issue of some sort that terminates the session, retuning an errorCode of 390111, and a message of "Session no longer exists.  New login required to access the service". We add a simple check to fail fast and raise a DatabaseError, which returns the query ID and the query status FAILED_WITH_ERROR.
=> SNOW-491028 Fail Fast for Empty Resp Object

src/snowflake/connector/result_batch.py, test/integ/pandas/test_arrow_pandas.py
=> SNOW-418514 Add Typed DataFrames and Empty Tables

test/integ/test_cursor.py
=> Add Old Driver Decorator

.github/workflows/build_test.yml, .github/workflows/create_req_files.yml, Jenkinsfile, ci/build_darwin.sh, ci/build_linux.sh, ci/docker/connector_build/Dockerfile, ci/test_darwin.sh, setup.py, tox.ini
=> SNOW-474073 Add 3.10 Support

setup.py
Fixes SNOW-518467
Remove support and and ecosystem team email.
=> SNOW-518467 updated contact e-mail address

DESCRIPTION.rst, src/snowflake/connector/version.py
=> SNOW-518496: Bumped up PythonConnector PATCH version from 2.7.1 to 2.7.2

ci/build_windows.bat
=> Add 3.10 to Windows Build

ci/test_linux.sh, tox.ini
=> SNOW-474074 Add 3.10 to Test Linux

src/snowflake/connector/file_transfer_agent.py, test/integ/test_put_get.py, test/unit/test_put_get.py
=> SNOW-499333 Add GET Empty File Handling

src/snowflake/connector/file_transfer_agent.py, test/unit/test_put_get.py
=> SNOW-513998 Fix Storage Credential Error

src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.hpp, test/integ/pandas/test_arrow_pandas.py
=> SNOW-474539 Add Timezone to Timestamp_TZ

src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, test/integ/pandas/test_arrow_pandas.py
Fixes SNOW-467996
Fix arrow decimal precision.
=> SNOW-467996 Negative Numbers Mangled for arrow_number_to_decimal

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-532795: Bumped up PythonConnector PATCH version from 2.7.2 to 2.7.3

.github/workflows/build_test.yml, .github/workflows/create_req_files.yml, Jenkinsfile, README.md, ci/wss.sh
Fixes SNOW-535873
This updates references of the `master` branch to `main`.
=> SNOW-535873 update references from master to main

.github/workflows/create_req_files.yml
Fixes SNOW-477347
Updating push branch to be dynamic
=> Update create_req_files pipeline

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes #922
Should be straightforward.
=> SNOW-499499 Make violating NOT NULL constraint raise IntegrityError

.github/workflows/create_req_files.yml
Relates to SNOW-477347
Removing some steps that are not needed.
=> SNOW-477347 remove unnecessary python setup

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
=> SNOW-499498 Raise InterfaceError instead of DatabaseError when trying to execute against a closed cursor

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-538916: Bumped up PythonConnector PATCH version from 2.7.3 to 2.7.4

.github/workflows/cla_bot.yml
=> adding github-actions

.github/workflows/build_test.yml, .github/workflows/create_req_files.yml
=> SNOW-470350 Remove 3.6 Tests from GitHub actions

setup.cfg
Fixes #NNNN
I found that there's a dependency that we list as a regular dependency (`pytz`), but also as a `development` requirement.
=> removing doubly listed dependency

src/snowflake/connector/__init__.py
Fixes #1046
Exports `SnowflakeConnection` so it can be referenced without type errors in applications.
=> SNOW-539182 export SnowflakeConnection

.gitignore, .pre-commit-config.yaml, src/snowflake/connector/cursor.py, src/snowflake/connector/network.py, src/snowflake/connector/sfdatetime.py, src/snowflake/connector/snow_logging.py, src/snowflake/connector/telemetry.py, src/snowflake/connector/util_text.py, test/integ/pandas/test_pandas_tools.py, test/integ/pandas/test_unit_arrow_chunk_iterator.py, test/integ/test_arrow_result.py, test/integ/test_cursor.py, test/integ/test_errors.py, test/integ_helpers.py, test/unit/test_errors.py, test/unit/test_session_manager.py
Fixes #NNNN
Just pre-commit things
=> pre-commit autoupdate

.github/workflows/build_test.yml
Fixes #NNNN
I'm trying out building wheel with `cibuildwheel`
=> switch to new build process

src/snowflake/connector/connection.py, test/unit/test_connection.py
Fixes #1093
By updating the kwargs that are passed to `SnowflakeConnection.connect` beforehand using the environment variable causes the proper APPLICATION to be sent in the request.
=> Set application from env var properly

setup.cfg
Fixes #1036
Modified setup.py line for pandas, reran unit-tests.
=> SNOW-581651 Support pandas < 1.5.0

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-582265: Bumped up PythonConnector PATCH version from 2.7.6 to 2.7.7

.github/workflows/jira_issue.yml, .gitignore, test/.gitignore
Fixes SNOW-587148
Updating some `.gitignore` stuff and updating asignee and components of generated Jiras
=> SNOW-587148 Jira creation adjustments

.github/workflows/cla_bot.yml
Fixes SNOW-587720
Please observe the issue [here](https://github.com/snowflakedb/snowflake-connector-python/runs/6360397769?check_suite_focus=true)
Hopefully this will fix the issue with our CLA bot automation.
=> SNOW-587720 update cla_bot repository name

.github/workflows/jira_issue.yml
Fixes SNOW-587148
I used the wrong assignee before.
=> SNOW-587148 assignee update

.github/workflows/jira_issue.yml
Fixes SNOW-587148
Last assignee update
=> SNOW-587148 Jira assignee update

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes SNOW-592211
Adding `kwargs` pass-through to `executemany` and updating an already existing test that to check corectness.
=> SNOW-592211 add kwargs to executemany

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-594137: Bumped up PythonConnector PATCH version from 2.7.7 to 2.7.8

setup.cfg
=> Update `author_email` in setup.cfg

.github/workflows/cla_bot.yml
=> adding Jenkins to bot accounts

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_37.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> SNOW-616990: Bumped up PythonConnector PATCH version from 2.7.8 to 2.7.9

DESCRIPTION.md, ci/build_docker.sh, ci/build_linux.sh, ci/docker/connector_build/Dockerfile, ci/docker/connector_test/Dockerfile, ci/set_base_image.sh, ci/test_docker.sh, ci/test_fips.sh, ci/test_fips_docker.sh, ci/test_linux.sh, pyproject.toml, setup.cfg, setup.py, src/snowflake/connector/arrow_iterator.pyx
Fixes SNOW-628190
Adding support for `pyarrow==8`.
This PR is the same as #1138 after I renamed the branch.
=> SNOW-628190 support pyarrow 8 and manylinux update

.github/workflows/snyk-issue.yml, MANIFEST.in, setup.cfg, src/snowflake/connector/cache.py, src/snowflake/connector/constants.py, src/snowflake/connector/converter.py, src/snowflake/connector/converter_issue23517.py, src/snowflake/connector/network.py, src/snowflake/connector/ocsp_asn1crypto.py, src/snowflake/connector/ocsp_snowflake.py, src/snowflake/connector/ssl_wrap_socket.py, test/integ/pandas/test_arrow_chunk_iterator.py, test/unit/test_cache.py, test/unit/test_ocsp.py, tox.ini
=> SNOW-574657 in-memory cache impementation

DESCRIPTION.md, src/snowflake/connector/network.py
Fixes SNOW-612517
It seems like there was a bug in our old gzip compression code, because `GzipFile` was never closed. One user hit this issue, I believe that the issue is very dependent on their gzip library's code as we were unable to  reproduce the issue. This user has been testing this issue for days without encountering the issue since. I'd like to merge this fix pre-maturely, because I see no harm in it even if didn't fully fix the issue.
=> SNOW-612517 disable gzip compression

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/connection_diagnostic.py
Fixes #SNOW-560689
code - Not sure if needed
=> SNOW-560689 adding connection diagnostics

DESCRIPTION.md, setup.cfg
=> Update numpy requirement from <1.23.0 to <1.24.0

DESCRIPTION.md, setup.cfg, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_37.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Fixes #1206 
In this PR I add the missing lower version pin to our new dependency from #1195
=> SNOW-634755 fix typing_extensions version pin

.github/workflows/build_test.yml
Fixes SNOW-636384
Brownout period is making our jobs fail, so the version bump is already necessary.
=> SNOW-636384 bump macos used to build package

src/snowflake/connector/pandas_tools.py, test/integ/pandas/test_pandas_tools.py
Description
table_type could support transient table as well, which is more
flexible comparing to create_temp_table
Testing
Added integ test
Fixes #NNNN
=> SNOW-630797 Support table_type in pandas_tools

.pre-commit-config.yaml
Fixes SNOW-640954
This PR makes sure that `from __future__ import annotations` is added to all `.py` file in `src/snowflake/connector` automatically.
=> SNOW-640954 add new automatic future import hook

src/snowflake/connector/cursor.py, test/integ/pandas/test_arrow_pandas.py, test/integ/test_cursor.py
=> SNOW-642562-yuwang: cursor.fetch_pandas_batches() when executing asynchronously

.github/pull_request_template.md
Fixes SNOW-646318
Adding a new question to our PR template to act as a reminder to add telemetry messages.
=> SNOW-646318 Update pull_request_template.md

src/snowflake/connector/auth_okta.py
Fixes SNOW-648958
This change adds support in the Python driver for the Okta OIE.
=> SNOW-648958 Support for Okta OIE

src/snowflake/connector/result_batch.py, src/snowflake/connector/result_set.py, test/integ/pandas/test_arrow_pandas.py
=> SNOW-641540 Fix dtypes of fetch_pandas_all for empty result

src/snowflake/connector/result_batch.py, src/snowflake/connector/result_set.py, test/integ/pandas/test_arrow_pandas.py
Reverts snowflakedb/snowflake-connector-python#1226
=> Revert "SNOW-641540 Fix dtypes of fetch_pandas_all for empty result"

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes [snowflake-sqlalchemy/#244](https://github.com/snowflakedb/snowflake-sqlalchemy/issues/244)
SQLAlchemy's batch delete and update operations (in ORM) return
rowcount of those operations after it closes the cursor. This
fails to work with Snowflake engine and returns None because we
are erasing the last known rowcount when the cursor is closed.
More information on the issue can be read on the original issue:
https://github.com/snowflakedb/snowflake-sqlalchemy/issues/244
In comparison the SQLite DB-API …
=> SNOW-647539 Closing the cursor erases the last rowcount

src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, src/snowflake/connector/ocsp_snowflake.py, src/snowflake/connector/telemetry.py, src/snowflake/connector/telemetry_oob.py, test/unit/test_telemetry.py, test/unit/test_telemetry_oob.py
Fixes SNOW-654808, SNOW-652000
- add source to basic telemetry data
- add a classmethod to `TelemetryData` to construct from a dict
=> SNOW-654808, SNOW-652000: Add field source to basic telemetry data and refactor Telemetry data

src/snowflake/connector/pandas_tools.py, src/snowflake/connector/telemetry.py
=> SNOW-646302: Add telemetry for write_pandas

ci/docker/connector_test_fips/Dockerfile
Fixes [SNOW-442275](https://snowflakecomputing.atlassian.net/browse/SNOW-442275)
Reduces docker image size by reducing the number of layers created by yum install commands and cleaning the cache afterwards.
=> SNOW-442275: Reduce docker image size

src/snowflake/connector/pandas_tools.py
Fixes #679 
- `pd_writer` functionality has to be used with `snowflake-sqlalchemy` as the `DataFrame.to_sql` function requires a sqlalchemy engine, so the tests are in a separate PR in the `snowflake-sqlalchemy` repository.
Adding `write_pandas` non-deprecated keyword arguments to both `pd_writer` and `make_pd_writer` so users can actually use them in conjunction with `DataFrame.to_sql` and `snowflake-sqlalchemy`.
=> SNOW-344567: Exposing write_pandas keyword arguments in pd_writer

test/integ/test_errors.py
Fixes #683755
Fixes a test failure caused by the changes associated with 683755
=> Updated test errors to support new error code

setup.cfg
Signed-off-by: mvashishtha <mahesh@ponder.io>
Fixes #1305 
Update pandas requirement by imitating #1036
=> SNOW-686297: Support pandas 1.5.

DESCRIPTION.md
=> Update DESCRIPTION.md to include pandas version bump

test/integ/pandas/test_pandas_tools.py, test/integ/test_bindings.py, test/integ/test_cursor.py, test/integ/test_dataintegrity.py, test/integ/test_dbapi.py, test/integ/test_put_get.py, test/integ/test_put_get_compress_enc.py, test/integ/test_put_get_medium.py, test/integ/test_put_get_user_stage.py, test/integ/test_put_get_with_aws_token.py, test/integ/test_put_get_with_azure_token.py, test/integ/test_put_get_with_gcp_account.py, test/randomize.py, test/unit/test_gcs_client.py, test/unit/test_ocsp.py
=> SNOW-690343: Fixing import errors for olddriver tests

Jenkinsfile, ci/test.sh
Fixes #SNOW-670581
Use new s3 bucket as a part of sfc-dev migration.
=> SNOW-670581 move to new s3 buckets

DESCRIPTION.md, tested_requirements/requirements_310.reqs, tested_requirements/requirements_37.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Fixes SNOW-693789
Just missing changelog details
=> SNOW-693789: adding missing CHANGELOG for v2.8.2 release

SECURITY.md
Adding contact details in the security tab
Adding contact details for security issues
3. Fill out the following pre-review checklist:
4. Please describe how your code solves the related issue.
=> Update security tab

src/snowflake/connector/test_util.py, test/helpers.py, test/integ/test_multi_statement.py
Fixing many issues reported here: <https://snowflakecomputing.atlassian.net/jira/software/c/projects/SNOW/issues/SNOW-703343?jql=project%20%3D%20%22SNOW%22%20AND%20assignee%20%3D%20%2261027a219798100070592b20%22%20ORDER%20BY%20created%20DESC>
=> SNOW-199087 Moved functions using pytest to test folder

.github/workflows/semgrep.yml, Jenkinsfile
SNOW-667402:Security Update. 
This PR creates/updates the Semgrep static analysis workflow. Local semgrep rules have been deleted. If your repo had a semgrep stage in the Jenkinsfile, we attempted to delete it. Please review changes and merge them as soon as possible.
[Announcement](https://snowflake.slack.com/archives/C02BTC3HY/p1661797484408489)
=> SNOW-667402:Semgrep workflow update

.github/dependabot.yml, .github/workflows/build_test.yml, .github/workflows/create_req_files.yml, .github/workflows/jira_close.yml, .github/workflows/jira_issue.yml, .pre-commit-config.yaml, test/integ/test_bindings.py
Fixes SNOW-680550
Bumping all used actions to newest versions before action warnings become an issue. Dependabot will now open PRs for bumping GitHub action versions too.
=> SNOW-680550 bump GitHub actions used

DESCRIPTION.md, tested_requirements/requirements_310.reqs, tested_requirements/requirements_37.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Fixes #NNNN
Adding necessary changes in preparation to release `v2.9.0`
=> 2.9.0 release

.github/repo_meta.yaml
Fixes SNOW-711893
following the yaml: https://github.com/snowflakedb/snowflake_template_repository/blob/main/.github/repo_meta.yaml
=> SNOW-711893: update repo_meta

src/snowflake/connector/auth/_auth.py, src/snowflake/connector/connection.py, src/snowflake/connector/network.py, test/unit/test_auth_mfa.py
Fixes #1390 SNOW-721779
I've made a mistake when rewriting code in #1215, in this PR I fix this issue. MFA tokens should be properly cached again. We don't have automated tests for this, but I've tested this manually.
=> SNOW-721779 fix MFA token cache logic

test/integ/test_async.py
Fixes #NNNN
When looking at why https://github.com/snowflakedb/snowflake-connector-python/actions/runs/3887610176/jobs/6634375598 was failing, I found and fixed the issue. We should introduce `mypy` type checking ASAP.
=> fix flaky test issue

src/snowflake/connector/cursor.py
Fixes #1271
Changes in the log level
=> Changed log level when PyArrowIterator failed to be imported

src/snowflake/connector/cursor.py, test/integ/pandas/test_arrow_pandas.py
Fixes SNOW-725840
Adds tests and fixes to allow async execution while using fetch_arrow_all and fetch_arrow_batches
Currently, async execution of these API methods results in errors of the following form:
- For fetch_arrow_all:
`snowflake.connector.errors.NotSupportedError: Unknown error`
- For fetch_arrow_batches:
`AttributeError: 'NoneType' object has no attribute '_fetch_arrow_batches'`
=> SNOW-725840 Async support for arrow fetch functions

src/snowflake/connector/auth/_auth.py, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, test/integ/conftest.py, test/integ/test_cursor.py, test/integ/test_session_parameters.py
Fixes #SNOW-678541
Do for HTAP changes is [here](https://docs.google.com/document/d/1Q1svmjM_kd1eCdT5MH9QMoLqAOOmIPdRTDbpfABtBMs). The corresponding jdbc commit is here: https://github.com/snowflakedb/snowflake-jdbc/pull/1154/files
=> SNOW-678541: snowflake-connector-python all integ tests successful

MANIFEST.in, samples/README.md, samples/auth_by_key_pair_from_file.py
=> SNOW-121291: Adding sample for authentication by key pair from file 

src/snowflake/connector/arrow_context.py, src/snowflake/connector/converter.py
=> SNOW-743465: update mypy import

src/snowflake/connector/cursor.py
updated execute_async() method's docstring.
Fixes #NNNN
=> SNOW-647590: update execute_async's desc to not support PUT/GET

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Fixes SNOW-754180
Adds a `needs triage` label to new feature requests
=> SNOW-754180 Update feature requests to include a `needs triage` label

.github/workflows/stale_issue_bot.yml
For some reason github workflow does not recognize this field. It works perfectly on my local machine
Fixes SNOW-756460
=> SNOW-756460 Remove description in stale_issue_bot.yml

DESCRIPTION.md, src/snowflake/connector/cursor.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/storage_client.py, test/integ/test_put_get.py
Fixes #SNOW-706838
Adding a parameter that allows to skip file uploads to stage in case contents of the remote file match the content of the local file.
=> SNOW-706838 add option to skip upload file if content matches

DESCRIPTION.md, src/snowflake/connector/cursor.py
=> SNOW-777893: improve type hint of SnowflakeCursor.execute

DESCRIPTION.md, src/snowflake/connector/pandas_tools.py, test/integ/pandas/test_pandas_tools.py
Fixes #NNNN
See context [here](https://snowflake.slack.com/archives/C02KH7E6SHX/p1681258153497469)
=> SNOW-789699: Fix write_pandas when pandas dataframe has binary data

test/integ/test_put_get.py, test/integ/test_put_get_user_stage.py, test/integ/test_put_get_with_gcp_account.py
=> remove mock patching of cursor.SnowflakeFileTransferAgent

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-795117: Bumped up PythonConnector PATCH version from 3.0.2 to 3.0.3

.github/workflows/cla_bot.yml
Fixes #NNNN
Based on https://github.com/contributor-assistant/github-action/issues/130 this might solve the issue in https://github.com/snowflakedb/snowflake-connector-python/actions/runs/4745800989/jobs/8432595007?pr=1513.
=> testing whether GitHub action permissions are causing CLA issues

src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/nanoarrow.h, src/snowflake/connector/cpp/ArrowIterator/nanoarrow.hpp, test/integ/pandas/test_arrow_pandas.py
=> decimal support

src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/DecimalConverter.cpp
=> Snow 773928 nanoarrow table iterator decimal support

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
=> [SNOW-812398] Add ability to return raw response json from python-connector

test/integ/test_cursor.py
SNOW-812398
Fixes test failures introduced in earlier PR. 
Follow up to #1556
=> [SNOW-812398] Ignore tests on olddriver

test/unit/test_url_util.py
Fixes SNOW-761004
Follow up to https://github.com/snowflakedb/snowflake-connector-python/pull/1480#discussion_r1145500797
=> SNOW-761004 fixing issue committed

DESCRIPTION.md, src/snowflake/connector/constants.py, test/integ/test_cursor.py
Fixes #SNOW-733083
Add support for GEOMETRY type.
=> SNOW-733083 Add GEOMETRY type

test/integ/test_session_parameters.py
=> fix htap tests on jenkins

ci/build_darwin.sh
=> Support Building of ARM CI/CD

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes SNOW-812398
Reverts https://github.com/snowflakedb/snowflake-connector-python/pull/1556
=> [Revert][SNOW-812398]Add ability to return raw response json from python-connector

DESCRIPTION.md, test/integ/test_connection.py
=> [SNOW-837919] Fix test by adding exception handling for grant query

src/snowflake/connector/cpp/ArrowIterator/flatcc/flatcc_assert.h, src/snowflake/connector/cpp/ArrowIterator/flatcc/flatcc_epilogue.h, src/snowflake/connector/cpp/ArrowIterator/flatcc/portable/paligned_alloc.h, src/snowflake/connector/cpp/ArrowIterator/flatcc/portable/pdiagnostic.h, src/snowflake/connector/cpp/ArrowIterator/flatcc/portable/punaligned.h, src/snowflake/connector/cpp/ArrowIterator/nanoarrow.c, src/snowflake/connector/cpp/ArrowIterator/nanoarrow.h, src/snowflake/connector/cpp/ArrowIterator/nanoarrow.hpp, src/snowflake/connector/cpp/ArrowIterator/nanoarrow_device.c, src/snowflake/connector/cpp/ArrowIterator/nanoarrow_device.h, src/snowflake/connector/cpp/ArrowIterator/nanoarrow_ipc.c, src/snowflake/connector/cpp/ArrowIterator/nanoarrow_ipc.h, src/snowflake/connector/version.py
using commit: https://github.com/apache/arrow-nanoarrow/tree/01691852306c5db7659991a26f7a0877b4ae13b3
Fixes #NNNN
=> bump nanoarrow dependency to v0.2.0

src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowIterator.hpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/TimeStampConverter.cpp, src/snowflake/connector/cpp/ArrowIterator/TimeStampConverter.hpp
=> SNOW-831854: Add error handling logic

test/unit/test_result_batch.py
=> SNOW-736326: Fix old driver test

DESCRIPTION.md, src/snowflake/connector/constants.py
Fixes SNOW-830394
Just a better explanation to what the new feature can do
=> SNOW-830394 adding better configuration file changelog entry

setup.cfg, src/snowflake/connector/connection.py, src/snowflake/connector/description.py, src/snowflake/connector/telemetry.py, src/snowflake/connector/version.py
=> SNOW-848033: backend prerelease version compatibility

src/snowflake/connector/pandas_tools.py
=> SNOW-735220: update documentation of pd_writer

.github/workflows/build_test.yml
=> SNOW-823926: Upload test coverage for lambda tests

DESCRIPTION.md, src/snowflake/connector/storage_client.py
Fixes #1490
We shouldn't delete files in `__del__` without lock. See details in https://stackoverflow.com/a/66340298
=> SNOW-767903: Resolve the race condition of deleting temp file when running PUT

.github/workflows/cla_bot.yml, CONTRIBUTING.md
Fixes #NNNN
CLA document is moved to a new repo, we need to update the link. This should be automated in the future.
=> Update CLA document link

src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp, src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp
=> fix ArrowStringView

src/snowflake/connector/cache.py
Fixes SNOW-877652
follow up item: https://snowflakecomputing.atlassian.net/browse/SNOW-877785
=> SNOW-877652: Remove __del__

test/integ/test_load_unload.py, test/integ/test_put_get.py, test/integ/test_put_get_user_stage.py, test/unit/test_ocsp.py, test/unit/test_s3_util.py
Fixes #SNOW-874975
Move to new sfc-dev2 buckets.
=> SNOW-874975: Migrate out of sfc-dev1

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-879809: Bumped up PythonConnector MINOR version from 3.0.4 to 3.1.0

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-880185: 3.1.0a2 release preparation

src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/local_storage_client.py, test/unit/test_local_storage_client.py
Description
wb means open the file in write mode with truncation. What we
actually want is rb+
Testing
Tested locally
Fixes SNOW-874210
=> SNOW-874210 Fix localfs chunked upload/download

src/snowflake/connector/connection.py
Fixes #1648
As suggested by user in the original issue, using `list(sys.modules)` to make sure `RuntimeError: dictionary changed size during iteration` is not encountered when dictionary changes during iteration.
=> SNOW-870802: make log_telemetry_imported_packages threadsafe

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-896089: Bumped up PythonConnector PATCH version from 3.1.0 to 3.1.1

test/unit/test_telemetry_oob.py
Fixes SNOW-901898, clean up the buffer before the test
=> SNOW-901898: fix flaky oob test

src/snowflake/connector/config_manager.py, src/snowflake/connector/connection.py
Fixes SNOW-891470
In this way, this function can be called in Snowpark.
=> SNOW-891470: Refactor reading default connection into a function 

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-909591: Bumped up PythonConnector MINOR version from 3.1.1 to 3.2.0

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-912520: release nanoarrow based connector 3.3.0b1

DESCRIPTION.md, setup.cfg, src/snowflake/connector/sf_dirs.py, test/unit/test_configmanager.py
Fixes #1695 
In this PR I undo my ABC way of imitating `platformdirs` and I type things with a [Protocol](https://docs.python.org/3/library/typing.html#typing.Protocol) instead.
=> SNOW-893112 updated platformdirs usage

src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_arrow_iterator.pyx
=> SNOW-920889: remove unnecessary cython bytes copy

src/snowflake/connector/result_batch.py
=> SNOW-920889: remove code in code execution and change if statement

DESCRIPTION.md, src/snowflake/connector/auth/_auth.py, test/unit/test_auth.py
=> SNOW-923398: improve robustness in handling authentication response 

src/snowflake/connector/connection.py, src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_arrow_iterator.pyx, src/snowflake/connector/result_batch.py
=> SNOW-920889: remove check in cython and improve iterator creation

MANIFEST.in, src/snowflake/connector/nanoarrow_cpp/ArrowIterator/LICENSE.txt, src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow.h
=> SNOW-928212: use nanoarrow v0.3.0

src/snowflake/connector/cursor.py, test/integ/test_cursor.py
=> SNOW-927245: Introduce env var to control arrow behavior

test/integ/test_cursor.py
=> SNOW-920253: add tests for backend parameter

.github/workflows/build_test.yml, MANIFEST.in, setup.py, src/snowflake/connector/arrow_context.py, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp, src/snowflake/connector/nanoarrow_cpp/ArrowIterator/nanoarrow_arrow_iterator.pyx, src/snowflake/connector/result_batch.py, test/helpers.py, test/integ/conftest.py, test/integ/pandas/test_error_arrow_pandas_stream.py, test/integ/test_cursor.py, test/stress/dev_requirements.txt, test/stress/e2e_iterator.py, test/stress/local_iterator.py, test/stress/util.py, test/unit/test_error_arrow_stream.py
=> nanoarrow review feedbacks

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> SNOW-937634: Bumped up PythonConnector PATCH version from 3.2.1 to 3.3.0

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/connection_diagnostic.py, test/unit/test_connection_diagnostic.py
Fixes issues with the connection diagnostic failing to check OCSP and stages.
- [x ] I am adding a new automated test(s) to verify correctness of my new code
Connection diagnostics were failing because of the result on OCSP checks.  Fixed this to decrypt the byte responses.
=> Second attempt at fixing the diagnostics issues

src/snowflake/connector/cursor.py
=> Add Jira to one TODO in cursor.py

.github/workflows/build_test.yml, DESCRIPTION.md, setup.py, src/snowflake/connector/result_batch.py, test/unit/test_connection_diagnostic.py, tox.ini
=> SNOW-940615: fix pyarrow import if pyarrow iterator is not compiled

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-941050_python_connector_version_bump

DESCRIPTION.md, ci/test_fips_docker.sh, ci/test_lambda_docker.sh, setup.cfg, src/snowflake/connector/connection.py, src/snowflake/connector/encryption_util.py, src/snowflake/connector/file_util.py, src/snowflake/connector/ocsp_asn1crypto.py, test/integ/test_connection.py
Fixes SNOW-843716
- removing dep is a BCR, it broke SnowSQL in the previous commit.
- I reverted the commit, create a new PR with BCR change announcement
- this time let's also remove the property `only_use_openssl` as it's of no use, openssl will always be used
=> SNOW-843716: cryptography dep cleanup

.github/workflows/snyk-issue.yml, .github/workflows/snyk-pr.yml
=> PRODSEC-3611 fix GHA parsing

DESCRIPTION.md, src/snowflake/connector/vendored/urllib3/util/connection.py, test/integ/test_vendored_urllib.py
Fixes https://github.com/urllib3/urllib3/issues/1878 in vendored lib
This is a known issue for urllib: https://github.com/urllib3/urllib3/issues/1878#issuecomment-641534573 and the fix proposed by the maintainers is added in our code: https://github.com/urllib3/urllib3/issues/1878#issuecomment-641548977
=> Fix urllib bug in vendored library

test/unit/test_local_storage_client.py
Description
This is a long overdue improvement from early slack message from Brandon
Testing
unit test
Fixes SNOW-892716
Use Pathlib and with-statement to improve test
=> SNOW-892716 Improve localfs put/get test

test/integ/test_cursor.py
Fixes SNOW-958531
I'm improving a test to be less flaky, hopefully.
=> SNOW-958531 add retries for test_null_connection

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Preparing for `v3.4.1` release.
=> Bumped up PythonConnector MINOR version from 3.4.0 to 3.4.1

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> SNOW-nnnn: Bumped up PythonConnector MINOR version from 3.4.1 to 3.5.0

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/network.py, test/unit/test_connection.py
Fixes SNOW-901157
Adding a new feature where `SnowflakeConnection`s keep track of whether their master token has expired.
=> SNOW-901157 new expired feature

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> MINOR: Bumped up PythonConnector MINOR version from 3.5.0 to 3.6.0

DESCRIPTION.md, src/snowflake/connector/cursor.py
Fixes #1834
Table is now correctly typed. Note that pyarrow does not have good typing (Table is typed as "unknown"), but now at least the snowflake implementation is correct.
=> Fix pyarrow Table type hinting in cursor.py

DESCRIPTION.md, src/snowflake/connector/auth/webbrowser.py, src/snowflake/connector/connection.py, src/snowflake/connector/network.py, test/unit/test_auth_webbrowser.py
Fixes SNOW-877278
A mirror of https://github.com/snowflakedb/snowflake-jdbc/pull/1518.
=> SNOW-877278 Use console login URL for multiple SAML integration

ci/test_darwin.sh, ci/test_linux.sh, ci/test_windows.bat
https://ci-dev-122.int.snowflakecomputing.com/job/ReleasePythonConnector/31/console Every environment is green now
=> SNOW-1013942: Replace `--external_wheels` with `--installpkg` in tox

DESCRIPTION.md, src/snowflake/connector/config_manager.py, test/unit/test_configmanager.py
Fixes #1855
Change format of bad config permissions warning message
=> More readable permission warning message

src/snowflake/connector/cursor.py
This is a small PR with two two type hint fixes.
=> Fix type hints of SnowflakeCursor.describe and SnowflakeCursor. _describe_internal

.github/workflows/build_test.yml
=> SNOW-1041836: bump version of cibuildwheel to fix ci/cd

test/integ/sso/test_unit_sso_connection.py
- **Fix typo in comment**
Fixes SNOW-1061248
Typo be gone!
=> SNOW-1061248: Fix misspelling in test comment

DESCRIPTION.md, src/snowflake/connector/version.py
Fixes #NNNN
Preparation for v3.7.1 release.
=> Bumped up PythonConnector version from 3.7.0 to 3.7.1

tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Fixes #NNNN
Fixing the dependency files.
=> Update requirements files

DESCRIPTION.md, setup.cfg
Fixes #(https://snowflakecomputing.atlassian.net/browse/SNOW-1045652)
=> SNOW-1045652:Bump platformdirs upper bound

.github/repo_meta.yaml
=> SNOW-1254531: Update jira_area

DESCRIPTION.md, src/snowflake/connector/cursor.py, test/integ/test_cursor.py
Fixes SNOW-1247646
We should log the plain query at INFO level.
=> SNOW-1247646: Update the logging level from INFO to DEBUG when logging the executed query using `SnowflakeCursor.execute`

test/integ/test_cursor.py, test/integ/test_structured_types.py
Fixes #SNOW-1296812
Fix olddriver test and struct type tests on aws.
=> SNOW-1296812: fix merge gate tests

DESCRIPTION.md, src/snowflake/connector/pandas_tools.py, src/snowflake/connector/version.py, test/integ/pandas/test_pandas_tools.py, test/integ/test_cursor.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
Fixes SNOW-1308650
revert the code change introduced in PR: https://github.com/snowflakedb/snowflake-connector-python/pull/1899
this is a breaking change, we have yanked the release v3.8.0.
release a newer version 3.8.1 reverting the breaking change.
for the change itself, we should do the bug fix in the future in a non-breaking way.
=> SNOW-1308650: revert breaking change and release a newer version

test/unit/test_easy_logging.py
=> Skip old driver test in test_easy_logging.py

DESCRIPTION.md, src/snowflake/connector/s3_storage_client.py, test/unit/test_s3_util.py
=> SNOW-1258702:SnowSQL File Upload support for China

DESCRIPTION.md, src/snowflake/connector/connection.py, test/integ/test_easy_logging.py
=> SNOW-1292908:Initiatie log parser in SnowflakeConnection

ci/test_linux.sh, test/integ/test_autocommit.py, test/integ/test_converter_null.py, test/integ/test_cursor.py, test/integ/test_transaction.py
Fixes SNOW-1332387
after fixing the pipeline, there are some test failures. this PR tries to fix the test failures
=> SNOW-1332387: fix RT test failures

test/integ/pandas/test_arrow_pandas.py
Fixes #NNNN
The previous iteration of this test did not fetch the data with parameters enabled correctly. I've reorganized the test so that they should still be set when fetching data.
=> SNOW-0000000: Fix test_to_arrow_datatypes

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> MINOR: Bumped up PythonConnector MINOR version from 3.8.1 to 3.9.0

DESCRIPTION.md, src/snowflake/connector/s3_storage_client.py, test/unit/test_s3_util.py
=> Update accelarte turn off logic when connecting to china

DESCRIPTION.md, src/snowflake/connector/version.py
=> PATCH: Bumped up PythonConnector PATCH version from 3.9.0 to 3.9.1

DESCRIPTION.md
=> SNOW-0000000: Fix description log error

setup.cfg
Fixes #NNNN
This PR pins the pyarrow to the minimum version needed to support current features. This should have been included as part of #1907
=> SNOW-0000000: Update pyarrow dependency.

DESCRIPTION.md, src/snowflake/connector/connection.py, test/integ/test_connection.py
Fixes #NNNN
This is for reading the token file in SPCS now.
=> SNOW-1013595: Add support `token_file_path` in connection parameters

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/result_batch.py, test/integ/test_arrow_result.py
=> SNOW-1279205: add capability to debug arrow data

src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowTableIterator.cpp
Fixes SNOW-1367711
#1907 introduced a new log line that I was using to debug an issue related to timestamp scale. This change should not have been included in that PR and only adds noise.
=> SNOW-1367711: Remove incorrect error log message.

DESCRIPTION.md, src/snowflake/connector/storage_client.py, test/unit/test_storage_client.py
=> SNOW-1444663: fix SnowSQL PUT failed with a 400 error but the status shows as uploaded

test/integ/test_connection.py, test/integ/test_easy_logging.py, test/unit/test_configmanager.py, test/unit/test_connection.py, test/unit/test_easy_logging.py
Fixes #NNNN
While running unit tests we should not trigger configmanager warnings
=> fixing configmanager test warnings

.pre-commit-config.yaml, src/snowflake/connector/_query_context_cache.py, src/snowflake/connector/auth/_auth.py, src/snowflake/connector/connection.py, src/snowflake/connector/connection_diagnostic.py, src/snowflake/connector/cursor.py, src/snowflake/connector/errors.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_storage_client.py, src/snowflake/connector/network.py, src/snowflake/connector/result_batch.py, src/snowflake/connector/result_set.py, src/snowflake/connector/sf_dirs.py, src/snowflake/connector/storage_client.py, src/snowflake/connector/telemetry.py, src/snowflake/connector/telemetry_oob.py, test/integ/pandas/test_arrow_pandas.py, test/integ/pandas/test_pandas_tools.py, test/integ/test_connection.py, test/integ/test_cursor.py, test/integ/test_dbapi.py, test/integ/test_multi_statement.py, test/integ/test_put_get_with_gcp_account.py, test/stress/local_iterator.py, test/unit/test_gcs_client.py, tox.ini
There's no JIRA
I ran `pre-commit autoupdate` and fixed all issues detected by the new tool versions.
=> pre-commmit autoupdate and fixes

DESCRIPTION.md, src/snowflake/connector/auth/okta.py, src/snowflake/connector/connection.py, test/unit/mock_utils.py, test/unit/test_auth_okta.py, test/unit/test_connection.py
Fixes SNOW-1226666
this PR adds a new parameter to allow disable saml url check in okta authentication
=> SNOW-1226666: allow disabling saml url check in okta authentication

DESCRIPTION.md, src/snowflake/connector/ocsp_snowflake.py, test/unit/test_ocsp.py
Fixes #NNNN
Similar to https://github.com/snowflakedb/snowflake-jdbc/pull/1332
=> SNOW-1463842: URL-encode OCSP url

test/integ/test_arrow_result.py
Fixes SNOW-1369648
This PR adds a test that shows how structured type insert statements can currently use parameter binding to insert values.
=> SNOW-1369648: Add test for structured type parameter binding

test/integ/test_connection.py, test/unit/test_connection.py
=> Fix tests failure because of behavior change of server side error message and error code

.github/pull_request_template.md, .github/workflows/port_changes_to_sp.yml
Fixes #NNNN
Test: unrelated SP PR: https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/116
=> SNOW-1266560: Add github merge gate port sp changes

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/result_set.py
=> SNOW-806291: Fix Snowpark much slower than Spark Connector on  Databricks (for collect() and toPandas())

DESCRIPTION.md, setup.cfg
testing PR: https://github.com/snowflakedb/snowflake-connector-python/pull/2002
=> SNOW-1538754: Update keyring upper bound to 26

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> Bump python connector to 3.12.0

DESCRIPTION.md, src/snowflake/connector/network.py, test/unit/test_renew_session.py
=> SNOW-1546127: Fix python connector log leaking token inside http response body

src/snowflake/connector/connection.py, src/snowflake/connector/errors.py, src/snowflake/connector/network.py, src/snowflake/connector/ocsp_snowflake.py
Fixes SNOW-1563453
code clean as oob telemetry is not used
remove oob telemetry usage in connector
=> SNOW-1563453: remove oob telemetry usage in connector

.github/workflows/build_test.yml, setup.cfg, src/snowflake/connector/aio/__init__.py, src/snowflake/connector/aio/_connection.py, src/snowflake/connector/aio/_cursor.py, src/snowflake/connector/aio/_network.py, src/snowflake/connector/aio/auth/__init__.py, src/snowflake/connector/aio/auth/_auth.py, src/snowflake/connector/aio/auth/_by_plugin.py, src/snowflake/connector/aio/auth/_default.py, test/integ/aio/test_connection_async.py, tox.ini
Fixes SNOW-1617614
- reorganized POC code according to coding
- set up test pipelines
=> SNOW-1617614: asyncio network implementation, test set up

DESCRIPTION.md, setup.cfg, test/unit/test_dependencies.py, tox.ini
Fixes SNOW-1620333
unpin cryptography and add deprecation detection so that we can detect any API that will be deprecated in a future cryptography version and used by us
=> SNOW-1620333: unpin cryptography and add deprecation detection

DESCRIPTION.md, src/snowflake/connector/auth/_auth.py, src/snowflake/connector/auth/okta.py, src/snowflake/connector/auth/webbrowser.py, src/snowflake/connector/connection.py, test/integ/test_connection.py
Fixes #1869
This PR ensures we use `login_timeout` instead of `_login_timeout` internally. `login_timeout` is a property does type casting to integer.
4. (Optional) PR for stored-proc connector: NA
=> SNOW-1571763 fix login timeout read pattern

ci/test_fips.sh, src/snowflake/connector/aio/_network.py, src/snowflake/connector/aio/_ocsp_asn1crypto.py, src/snowflake/connector/aio/_ocsp_snowflake.py, src/snowflake/connector/aio/_ssl_connector.py, test/unit/aio/test_ocsp.py
=> SNOW-1348650: implement ocsp validation

README.md
Fixes SNOW-1432591
as per request, we include a section on disabling telemetry
=> SNOW-1432591: update readme on disabling telemetry

DESCRIPTION.md, src/snowflake/connector/util_text.py, test/unit/test_text_util.py
Fixes SNOW-1362666
https://github.com/snowflakedb/snowflake-connector-python/issues/1937
the previous string generation is affected by the global seed which can cause collision.
this affects feature like write pandas which uses this function to create temp stage.
with the fix, it greatly lower the possibility of having string collision  …
=> SNOW-1362666: improve random string generation

src/snowflake/connector/network.py, test/unit/test_network.py
=> SNOW-1524206: introduce a private parameter to enable raising raw http error not handled by connector logic

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, test/integ/test_async.py
Fixes SNOW-1625324
Improve error handling logic for async query fetch
https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/182
=> SNOW-1625324: improve error handling for async query

src/snowflake/connector/aio/__init__.py, src/snowflake/connector/aio/_connection.py, src/snowflake/connector/aio/_cursor.py, src/snowflake/connector/aio/_network.py, src/snowflake/connector/aio/_result_batch.py, src/snowflake/connector/aio/_result_set.py, src/snowflake/connector/aio/_time_util.py, test/helpers.py, test/integ/aio/conftest.py, test/integ/aio/test_arrow_result_async.py, test/integ/aio/test_boolean_async.py, test/integ/aio/test_concurrent_create_objects_async.py, test/integ/aio/test_connection_async.py, test/integ/aio/test_converter_async.py, test/integ/aio/test_converter_more_timestamp_async.py, test/integ/aio/test_converter_null_async.py, test/integ/aio/test_cursor_async.py, test/integ/aio/test_cursor_context_manager_aio.py, test/integ/aio/test_dataintegrity_aio.py, test/integ/aio/test_daylight_savings_aio.py, test/unit/aio/test_result_batch_async.py, tox.ini
=> Snow 1572213 implement result set iterator

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_38.reqs, tested_requirements/requirements_39.reqs
=> PATCH: Bumped up PythonConnector PATCH version from 3.12.1 to 3.12.2

src/snowflake/connector/aio/_cursor.py, test/integ/aio/test_cursor_async.py
=> SNOW-1572316: async query timer bomb

test/integ/test_connection.py
=> Fix a test to align with server side BCR

src/snowflake/connector/aio/_network.py, test/unit/aio/test_retry_network_async.py, test/unit/aio/test_session_manager_async.py
=> fix network implementation and add unit test

DESCRIPTION.md, src/snowflake/connector/_utils.py, src/snowflake/connector/cursor.py, test/integ/test_cursor.py, test/unit/test_util.py
Fixes #NNNN
Record whether the timer is executed to cancel the query to give more informative error information
https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/191
=> SNOW-802436: improve error message for sql execution cancellation due to timeout

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/constants.py, src/snowflake/connector/network.py, test/unit/test_connection.py, test/unit/test_util.py
Fixes #NNNN
Improve error message when hitting ssl related error
=> SNOW-799381: improve error message when hitting ssl related error

test/integ/test_connection.py, test/unit/test_connection.py
=> SNOW-1760173: fix test failure

src/snowflake/connector/aio/_result_batch.py
=> SNOW-1759076: async for support in cursor get result batches

src/snowflake/connector/aio/__init__.py, src/snowflake/connector/aio/_connection.py, src/snowflake/connector/aio/_cursor.py, src/snowflake/connector/aio/_file_transfer_agent.py, src/snowflake/connector/aio/_network.py, src/snowflake/connector/aio/auth/_auth.py, test/integ/aio/test_connection_async.py, test/integ/aio/test_cursor_async.py, test/integ/aio/test_dbapi_async.py, test/integ/aio/test_errors_async.py, test/integ/aio/test_large_result_set_async.py
=> SNOW-1763960: clean up todos in code base

README.md
Fixes SNOW-1760502
Just adding a new section to the README.
=> SNOW-1760502 Update README.md

DESCRIPTION.md, src/snowflake/connector/azure_storage_client.py, src/snowflake/connector/util_text.py, test/integ/test_put_get.py
Fixes SNOW-1778088
In this PR I fix a bug where files uploaded to Azure blob storage in pieces would be missing their MD5 hashes. Azure blob storage calculates these for small files automatically, but we need to do this manually for large files.
Unaffected.
=> SNOW-1778088 azure md5

DESCRIPTION.md, src/snowflake/connector/version.py
Fixes #NNNN
Preparation for 3.13.0 release.
=> release 3.13.0

.github/workflows/create_req_files.yml, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_39.reqs
=> bump gh action

src/snowflake/connector/auth/_auth.py, src/snowflake/connector/cache.py, src/snowflake/connector/encryption_util.py, src/snowflake/connector/file_util.py, src/snowflake/connector/ocsp_snowflake.py, src/snowflake/connector/storage_client.py, src/snowflake/connector/util_text.py, test/extras/run.py, test/unit/test_ocsp.py
=> SNOW-1902019: Python CVEs january batch

src/snowflake/connector/cursor.py, src/snowflake/connector/pandas_tools.py, test/integ/pandas/test_pandas_tools.py
=> SNOW-1902019: Python CVEs january batch 2

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_39.reqs
=> Release version 3.13.1

test/integ/test_cursor.py
Fixes #SNOW-1949003
Skip test of a new functionality that is not yet released.
=> SNOW-1949003: Skip test until Snowflake 9.4 release

DESCRIPTION.md
=> Update 3.14 release notes

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_39.reqs
=> 3.14-Update Requirements

tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_39.reqs
=> Update version 3.14.0 in requirements

test/integ/test_connection.py
=> SNOW-1959352 disable test_connection::test_bogus

.github/workflows/build_test.yml
=> SNOW-1960930: Update GH runner to ubuntu-latest

.github/CODEOWNERS
The project is in good hands, I don't need to part of the notifications anymore.
=> I think it's time to retire from snowflake-connector-python

ci/test_linux.sh, test/unit/test_wiremock_client.py
=> enable wiremock healthcheck test on jenkins

test/integ/test_cursor.py
=> SNOW-1977987 fix LOB size change impacted integration tests

src/snowflake/connector/auth/oauth_code.py
=> SNOW-1825495 refactoring/fields renaming in OAuth authenticator

src/snowflake/connector/auth/_auth.py, src/snowflake/connector/cache.py, src/snowflake/connector/token_cache.py, test/integ/sso/test_unit_mfa_cache.py, test/unit/test_linux_local_file_cache.py
=> SNOW-1825624: Refactor token cache before applying security changes

.github/workflows/build_test.yml
=> Cancel older builds on GH Actions

test/integ/test_cursor.py
=> SNOW-1949054: Reenable to_file test

.github/workflows/build_test.yml
=> NO-SNOW: Run test when targeting branches other than main

.pre-commit-config.yaml, license_header.txt
=> SNOW-1915375: disable license precommit hook

src/snowflake/connector/auth/_http_server.py, src/snowflake/connector/connection.py
=> SNOW-1825621: fix linter errors

src/snowflake/connector/file_lock.py, src/snowflake/connector/token_cache.py, test/unit/test_linux_local_file_cache.py
=> SNOW-1825624: Secure file token cache

src/snowflake/connector/auth/_oauth_base.py, src/snowflake/connector/auth/oauth_code.py, src/snowflake/connector/connection.py, test/unit/test_oauth_token.py
1. client secret should be required
2. extraction of connection parameters check that's common between oauth code and client credentials flows
=> NO-SNOW make client secret required in oauth code

src/snowflake/connector/auth/_http_server.py, src/snowflake/connector/connection.py
=> SNOW-1825621 added a retry logic for binding OAuth http server to a port

src/snowflake/connector/connection.py, test/unit/test_oauth_token.py
=> SNOW-1825495 reuse existing parameter to enable token cache

src/snowflake/connector/auth/_oauth_base.py
=> SNOW-1825495 use secret detector mask for variable logs

DESCRIPTION.md, src/snowflake/connector/azure_storage_client.py, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_storage_client.py, src/snowflake/connector/s3_storage_client.py, test/integ/test_connection.py, test/unit/test_gcs_client.py
Fixes #SNOW-1789751
Add support for the GCP regional and virtual endpoints
=> SNOW-1789751: Add GCP regional and virtual endpoints support

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py
Fixes SNOW-1896089
Lower some of the logs from info to debug to cleanup the output from the driver.
=> SNOW-1896089: Lower log level

src/snowflake/connector/auth/_auth.py, src/snowflake/connector/auth/oauth_code.py, src/snowflake/connector/token_cache.py
=> SNOW-1825495 some usability issues after pentesting

src/snowflake/connector/connection.py, test/data/wiremock/mappings/auth/pat/invalid_token.json, test/data/wiremock/mappings/auth/pat/successful_flow.json, test/unit/test_programmatic_access_token.py
unify pat behaviour across drivers
=> NO-SNOW Add PAT to authenticators allowing empty username, remove handling of PAT in password field

DESCRIPTION.md, src/snowflake/connector/connection.py, src/snowflake/connector/cursor.py, src/snowflake/connector/file_transfer_agent.py, src/snowflake/connector/gcs_storage_client.py, test/integ/test_connection.py, test/unit/test_gcs_client.py
Fixes SNOW-2032699
Use the Snowflake metadata response to define if the GCS virtual url should be used.
=> SNOW-2032699: Use GCS virtual url based on the stage response

src/snowflake/connector/cache.py, src/snowflake/connector/ocsp_snowflake.py
=> NO-SNOW acquiring a lock on local OCSP cache will use a timeout

DESCRIPTION.md
=> NO-SNOW update 3.14.1 release notes

DESCRIPTION.md
=> NO-SNOW Update release date

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-1993520 Patch python connector version bump

DESCRIPTION.md, setup.cfg
=> SNOW-2055494 fix proper boto min versions

src/snowflake/connector/connection.py, test/unit/test_oauth_token.py
=> SNOW-2061664 flatten OAuth refresh_token and pkce parameters

DESCRIPTION.md, src/snowflake/connector/ocsp_asn1crypto.py, src/snowflake/connector/tool/dump_ocsp_response.py, tox.ini
=> SNOW-2067577 OCSP: stop certificates chain traversal as soon as a trusted one met

DESCRIPTION.md, src/snowflake/connector/version.py
=> SNOW-2057797 Minor python connector version bump

tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_313.reqs, tested_requirements/requirements_39.reqs
=> SNOW-2057797 Update requirements files

ci/test_darwin.sh, ci/test_windows.bat
=> SNOW-1660409: Darwin tests fixed

.github/workflows/build_test.yml, src/snowflake/connector/constants.py, src/snowflake/connector/pandas_tools.py
=> SNOW-2092927: extend pandas tests for 403 issues 

src/snowflake/connector/constants.py, test/unit/test_auth_oauth_auth_code.py, test/unit/test_oauth_token.py
=> SNOW-2222046: Fix flaky tests

src/snowflake/connector/_utils.py, src/snowflake/connector/auth/_auth.py
=> SNOW-2103855: Authentication failures fixed with application data extension

.github/workflows/build_test.yml
Fixes #2314
Adding the windows-11-arm win_arm64 platform to build_test workflow. Tests was not verified because of the no access to secrets.
=> [BUILD] Add win_arm64 platform support

.github/workflows/build_test.yml
=> NO-SNOW disable yet failing Win-ARM64 tests

test/integ/test_connection.py
=> NO-SNOW: fix flaky tests on invalid proxy

DESCRIPTION.md, src/snowflake/connector/auth/_auth.py, src/snowflake/connector/auth/okta.py, src/snowflake/connector/auth/webbrowser.py, src/snowflake/connector/platform_detection.py, test/integ/test_connection.py, test/unit/test_detect_platforms.py
=> SNOW-2268606 zero timeout disables endpoint-based cloud platform detection

DESCRIPTION.md, src/snowflake/connector/cursor.py, test/unit/test_cursor.py
=> SNOW-2283945 use AWS regional endpoints when required for storing pandas frames

setup.cfg
=> [Async] Apply minimal dependencies versions

setup.cfg
Fixes [#2541]
snowflake-connector has no direct dependency on cffi and therefor should not list is as a dependency
=> remove cffi dependency

DESCRIPTION.md, src/snowflake/connector/version.py, tested_requirements/requirements_310.reqs, tested_requirements/requirements_311.reqs, tested_requirements/requirements_312.reqs, tested_requirements/requirements_313.reqs, tested_requirements/requirements_39.reqs
version bump + test requirements
=> Minor python connector version bump

.github/workflows/build_test.yml, tox.ini
=> SNOW-2021009: Improving CICD, flakiness fixes
