- chunk_downloader.py
- connection.py
- network.py
- ocsp_pyopenssl.py
This is a review seeking PR for @smtakeda (and @blandonnimrat)
It does test well for me on python3.5 and python2.7 but I would consider it as part of ongoing work to increase download concurrency safely.  Please feel free to provide feedback and criticism here and/or merge if you are happy enough with the intent.
I took some liberty in renaming existing mechanisms where it helped me make sense of the various pieces falling together but I can backtrack on them if they're undesired (named `access_url` -> `fetch`).
There is more overview in the commit logs as well.
> Session refactor

- setup.py
Sometimes there is no need or possibility (because of the package or setup-specific issues) to change the cryptography minor versions. This allows us to be less restrictive.
> setup.py: use less restrictive cryptography>=1.7,<1.8

- connection.py
- cursor.py
- test/conftest.py
- test/test_qmark.py
> SNOW-39905: SQLAlchemy doesn't work with paramstyle=qmark mode.

- network.py
- ocsp_pyasn1.py
- rfc6960.py
- setup.py
- ssl_wrap_socket.py
- test/test_ocsp_pyasn1.py
Fixed #59 by pulling back `pyasn1` based OCSP checks for Python 2.
Python 3 will continue using `asn1crypto` based OCSP checks for better performance.
> Reverted OCSP check code for Python2

- DESCRIPTION.rst
- setup.py
- version.py
- Limit the upper bound of `pycryptodome` for #65 
- Bumping up the version to 1.5.3
> Fixed pycryptodome 3.5.0 Mac issue. Bumping up the version to 1.5.3

- setup.py
Thanks to Pycryptdome team, the version dependency can be relaxed.
> exclude pycryptodome 3.5.0

- auth.py
- network.py
- setup.py
In 1.5.3, pyasn1 and pyasn1-modules were pulled back for Python 2 OCSP checks.
It caused an issue if the environment doesn't specify pyasn1 and have very old pyasn1, e.g., 0.1.x.
This change is mitigate it, but note this won't fix all cases where the environment may have incompatible combination of pyasn1 and pyasn1-modules, etc.
If you don't want to hit this type of issue, pin the versions in the applications.
> Adjusted pyasn1 and pyasn1-modules versions for Python2

- connection.py
- test/README.rst
From @tjj5036 
Tested via the following:
```
import snowflake.connector
cnx = snowflake.connector.connect(
account='testaccount',
host='https://myaccount.snowflakecomputing.com',
authenticator='OAUTH',
token=oauth_access_token)
cnx.close()
```
> Removes username restriction for OAuth.

- MANIFEST.in
Currently the cython components are not present in the source distribution of this library.
In https://github.com/conda-forge/snowflake-connector-python-feedstock/pull/19 we've attempted to build a conda-forge package for this, but failed due to missing source files.
> Ensure that the cython components are present in sdist

- docker/manylinux2010/Dockerfile-x86_64_base
- docker/manylinux2010/scripts/build_virtualenvs.sh
- docker/manylinux2010/scripts/entrypoint.sh
- scripts/build_connector_linux.sh
- scripts/build_inside_docker.sh
- scripts/install.bat
- scripts/install.sh
Tests are enabled for all os and python version available. except for python27
> Enable arrow tests on travis and appveyor

- pyproject.toml
I made a mistake by explicitly setting the `build-backend` to the default according to https://github.com/pypa/pip/issues/6230#issuecomment-459805348
By removing this we allow the build system to fall back to use setup.py install. This would allow us to install the connector without compiling our Arrow code, in case we wanted to do this, while defaulting to compiling it in most cases.
See the following install methods and notice the `--no-use-pep517` flag:
```
<$> pip install dist/snowflake-connector-python-2.2.10.tar.gz --no-use-pep517
Processing ./dist/snowflake-connector-python-2.2.10.tar.gz
Collecting azure-common<2.0.0
...
Installing collected packages: azure-common, urllib3, docutils, jmespath, six, python-dateutil, botocore, s3transfer, boto3, idna, chardet, certifi, requests, …
```
> SNOW-155318 remove explicit build-backend

- .github/workflows/build_test.yml
In light of the MANIFEST issue from last night I'm adding a test to build and install sdists.
This also makes it so not all tests wait for all build jobs to finish before starting, e.g.: linux tests will only wait for linux build jobs.
> SNOW-184712 add sdist test

- ci/test_darwin.sh
I forgot to change the test script for our Mac tests.
This removes the e.g. `3.5` folder from dist.
This was done in #376 on the build side
> SNOW-186696 fix mac tests with new folder structure

- .github/workflows/build_test.yml
- tox.ini
The issue right now with our coverage creation is that not all tests run in all jobs, so they need to combined before they could be uploaded to a service like codecov.io .
This PR aims to add that.
Each test job generates multiple testing environments at the end these are merged and uploaded for later.
When all tests passed then the merged coverage report are downloaded and merged one more time to get the overall coverage, this is then uploaded to codecov.io
> SNOW-173756 adding coverage reporting

- src/snowflake/connector/file_transfer_agent.py
While investigating GCP put issues I found that my fix in #354 was incorrect, this makes it so that we don't refresh client for GCP.
I don't think this hurt anything and it doesn't fix GCP puts right now, but I want to fix this issue anyways.
> SNOW-182731 fix aws client renewal when GCP needs renewal

- .gitignore
While exploring #397 today, I found that when I made mistakes working with Arrow, a core dump file was generated.
These are not ignored in this project's `.gitignore` today. This PR proposes that they should be ignored.
While touching `.gitignore`, I also noticed that some other common C object file extensions aren't currently ignored. This PR also proposes ignoring those.
Thanks for your time and consideration.
> SNOW-195747 add more object files, core dumps to gitignore

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Thanks for this great project!
While contributing here, I've found that the issue template that shows up when you click `New Issue` has language that is specific to bug reports, such as:
> Can you set logging to DEBUG and collect the logs?
In this PR, I'd like to propose creating separate templates for bug reports and feature requests. I think this will help to provide some structure and avoid unnecessary information in feature reports.
With the setup proposed in this PR, when someone clicks `New Issue`, they'll see this choice:
You can read more about having multiple issue templates [in the GitHub docs](https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).
Thanks for your time and consideration!
> SNOW-197039 add feature request issue template

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
This PR updates our new bug report issue template to ask for `pip freeze` instead of `pip list`.
This can speed up reproduction a little bit.
Edit: I also added a collapsible spot to put the pip freeze's output, so that it would not take up most of the screen anymore.
> SNOW-197039 Update BUG_REPORT.md

- setup.cfg
- tox.ini
`flake8` supports reading config values straight from `tox.ini`
This could remove `setup.cfg` from our repository.
> SNOW-195220 moved flake8 setting to tox.ini

- .github/workflows/jira_issue.yml
It's hard sometimes to find what issue a ticket is related to.
This change would add links to any Jiras created by GH actions.
`event.issue.html_url` seems to be the correct thing according to https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-example-when-someone-edits-an-issue
> SNOW-135600 added link to GH issue to Jiras created for them

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Unfortunately what I was going for doesn't work out because the lines to be considered part of the expanding list need to indented and nobody would want to indent those lines by hand, so I would like to revert back to using code blocks.
Current template: 
https://github.com/snowflakedb/snowflake-connector-python/issues/412
> SNOW-197039 reverting from expanding list to code block

- setup.py
The new `pytest` 6.1.0 release breaks support for its `pytest-rerunfailures` plugin, this PR pins us to use the not newest release of `pytest`.
> SNOW-199427 pin pytest

- src/snowflake/connector/auth.py
- src/snowflake/connector/options.py
- test/pandas/test_unit_options.py
- tox.ini
SNOW-197585 and #412 
Fixes an issue where on AWS Glue `setuptools` doesn't know what packages are installed.
> SNOW-197585 aws glue options

- test/lambda/test_basic_query.py
- tox.ini
SNOW-135960: Adding a few basic tests to test python-connector in AWS Lambda. 
* New tests are placed in lambda folder and plan is to run them only in a lambda function using "tox -e py{python-version}{-lambda}"
> SNOW-135960: add basic tests for lambda

- .github/workflows/build_test.yml
This is the short term solution to fix the new behaviour by `virtualenv`
> SNOW-207403 pin virtualenv until issue is fixed upstream

- .github/workflows/build_test.yml
- test/extras/run.py
So the original issue comes from a mixture of decisions: a behavior change introduced in Python 3.7.2's `venv` library, `virtualenv` using this new behavior in it's latest release and Windows always searching prepending the working directory to it's path.
So when `virtualenv` switched to using the new behavior of a redirector script (this is the venv behavior change). This makes it so that we don't need to copy dlls to the `venv`'s directory from the system wide Python install upon creation, saving space ultimately.
Then the redirector script execv'd to the system wide Python install and when the subprocess looked for the executable `python` it found it in the working directory, losing it's site-packages folder as the redirector script was not involved (it couldn't inject its …
> SNOW-207403 use sys.executable instead of bare python for subprocess

- src/snowflake/connector/pandas_tools.py
- test/pandas/test_pandas_tools.py
I added my own test to what was included in #362 but otherwise the same code changes are included.
So this PR fixes a couple of issues with `pandas_tools`.
- It makes it insert default/autoincrement column values.
- It allows customers to use a non-quoted syntax for column and table names.
Added integration tests to verify new code paths. It adds all of these while not causing a behavior change.
> Test PR 362

- .github/workflows/build_test.yml
More info: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> SNOW-206821 updated from add-path to environment files

- .github/workflows/jira_comment.yml
Something changed and now our comment action is posting useless comments on Jira: https://github.com/snowflakedb/snowflake-connector-python/actions/runs/320891610
I suspect this to be a GitHub Action change.
> SNOW-210112 fix variable usage in comment

- .github/workflows/jira_comment.yml
Undoes what #484 did and adds `github` in front of the objects, as this seems to work on line 20:
`TITLE: "${{ github.event.issue.title }}"`
> SNOW-210112 fix comments

- test/generate_test_files.py
- test/integ/test_put_get_user_stage.py
When refactoring some code I imported `generate_k_lines_of_n_files` instead of using a fixture,  but never updated how the function was called. Sorry!
> SNOW-215519 fixing a type hint and Jenkins test issues

- .github/workflows/build_test.yml
- src/snowflake/connector/arrow_result.pyx
- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
- tox.ini
Raises `cursor.py` coverage to ~100%. Covering the leftover part would only be questionably useful.
> SNOW-216517 improve cursor coverage

- .github/workflows/build_test.yml
- README.rst
- src/snowflake/connector/cpp/Logging/logging.cpp
- src/snowflake/connector/cpp/Logging/logging.hpp
Turns out that the issue with Python 3.8 was an unforeseen consequence of the new dll resolution (probably). Basically when importing anything from `snowflake.connector` the `__init__.py` imported `cursor.py`, which imported `arrow_result.py` which imported our C-extension, which then imported `snowflake.connector.snow_logging`, which imported `__init__.py` again.
So the proposed solution is to make `SnowLogger` creation lazy in our C-extensions. We only actually create our `SnowLogger`s upon the first logging message being logged.
> SNOW-143458 fix win python38

- .github/workflows/build_test.yml
- setup.py
Reverts snowflakedb/snowflake-connector-python#529 and disables parallel `tox` runs.
So `requests` refuses to work with dependencies that are outside of its pinned range.
We have been stuck on a little older `requests` because we have OCSP to patch into the new `requests` versions still. So this pin update of `urllib3` actually places it outside of the `requests` supported range.
This didn't show up in testing because our test environment must be using the new resolver of `pip`, although I am still verifying this. Because of parallel test execution of `tox`, it has been swallowing the outputs, so I need to turn this off and this will make my RCA a little longer. I can only thank myself for this 😞 
However; if a customer was disabling the new dependency resolver on purpose then the current …
> SNOW-222359 Revert "SNOW-222179 Update urllib3 requirement from <1.26.0,>=1.20 to >=1.20,<1.27.0"

- setup.py
This adds new URLs to our PYPI site: https://pypi.org/project/snowflake-connector-python/
Documentation: https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
An example of what this will look like: https://pypi.org/project/urllib3/
> SNOW-225351 added new URLs to to our setup.py

- setup.py
SNOW-230672
The newest release of `pyOpenSSL` breaks our compatibility.
See issue happening here: https://jenkins.int.snowflakecomputing.com/job/RT-FIPS-PyConnector36/1252/console
Test run on this branch: https://jenkins.int.snowflakecomputing.com/job/RT-FIPS-PyConnector36/1253/console
> SNOW-230672 pin pyOpenSSL more

- src/snowflake/connector/connection.py
- test/integ/test_async.py
Hi, first off, I'm super excited about the async features that seem to be on their way! Thanks for the great work.
I've noticed a typo in `SnowflakeConnection.get_query_status_throw_if_error` (extra indentation). This PR fixes it and tests the fix.
>  SNOW-80651 Fix typo in SnowflakeConnection.get_query_status_throw_if_error

- setup.py
The code makes use of modules that are not bundled with the Python standard library.
Ensure that "setuptools" is part of `install_requires`
> SNOW-237424 Declare dependency on setuptools

- setup.py
- src/snowflake/connector/arrow_iterator.pyx
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.hpp
- test/integ/pandas/test_arrow_pandas.py
SNOW-230346
Previously when returning NUMBERs with a non-zero scales need to be converted into doubles and switched out in the RecordBatches. Every time `AddColumn` and `DeleteColumn` were called they had to do a lot of resizing of hashmaps and copying a lot of values into new objects.
This PR removes the need to use `AddColumn` and `DeleteColumn` and instead operates on the underlying data and rebuilds RecordBatches only if necessary.
The query provided to me by support went from:
```
48.83139857795322
0.8859019490191713
```
to
```
2.7106516549829394
0.9343068830203265
```
Note that I got a lot more consistent numbers previously, I think my computer is just busier right now.
I was getting numbers close to `0.9` and `0.7` seconds.
> SNOW-230346 sped up arrow chunk rebuilding

- ci/test_fips.sh
SNOW-240266
New `cryptography` version (`3.3`) breaks compatibility with last FIPS version of OpenSSL.
> SNOW-240266 pin cryptography more aggressively when setting up FIPS test

- .github/workflows/build_test.yml
This will add a button for build-test workflow to run it manually . This will be useful for Releng team to run python tests on master  or any other branch as part of pre-release of server release is done to ensure it does not break python connector
> SNOW-208979 Add option to trigger Github Action Build/Test manually

- DESCRIPTION.rst
Description
Remove the reference to the change that adds support for MFA token caching.
This feature isn't available to customers yet, so it's not useful for customers to know that the
driver supports this feature.
> SNOW-236836 Remove the reference to the change that adds support for MFA token caching

- .github/workflows/build_test.yml
Adds an extra XML code coverage publishing, split from #557 
These XMLs will help us to debug what is going wrong with some codecov reports
> SNOW-230857 add extra coverage publishing for debugging purposes

- ci/build_linux.sh
- ci/build_windows.bat
Since we switched to `precommit-hooks` to run `flake8` tests, our regular flake8 settings have been unmaintained, so when we added the newly vendored libraries this started failing our Jenkins Windows build job.
I think we can simply remove the `flake8` tests from the build jobs (we have already removed it from the Mac and Linux build jobs) as `fix_lint` will run on GitHub for sure.
Successful jobs with this change:
Build: https://jenkins.int.snowflakecomputing.com/view/ClientMasterJobs/job/BuildPyConnector-Win/151
PY36: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector36-Win/148
PY37: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector37-Win/144
PY38: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector38-Win/33/
> SNOW-256116 retiring flake8 tests

- setup.py
- src/snowflake/connector/auth_keypair.py
`pyjwt` 2.0.0 was released [about a month ago](https://github.com/jpadilla/pyjwt/releases/tag/2.0.0). In that release, the behavior of `jwt.encode()` changed. It now returns a string instead of `bytes`, which is what caused the bug reported in #586 .
This PR proposes removing any version requirements on `pyjwt` in `snowflake-connector-python`. I think with the minor changes proposed in this PR, it's possible for `snowflake-connector-python` to work with both `pyjwt` 1.x and `pyjwt` 2.x.
* makes the one use of `jwt.encode()` in this project compatible with `pyjwt` 1.x and 2.x
* removes version constraint on `pyjwt`
This change would make `snowflake-connector-python` easier to install alongside other packages, because it relaxes a constraint placed on a popular and central package …
> SNOW-270639 pyjwt major bump and compatibility

- src/snowflake/connector/network.py
- tox.ini
This fix addresses the customer ticket SNOW-232777. 
A lot of Snowflake customers have strict data inspection requirements which requires them to use MiTM proxies. Python connector uses the Python Requests module to manage all the connectivity which internally takes care of connecting to proxies as well. However the Requests module internally uses urllib3 which internally uses http lib for connecting to proxies (python http lib > client.py > class HTTPConnection  > _tunnel() ). This routine only support HTTP/1.0 based CONNECT messages that do not need the presence of a HOST header in the connect request. The latest HTTP protocol RFC however mandates the presence of a HOST header in all CONNECT messages. 
This PR creates a subclass of the Requests HTTPAdapter class to gain access to the …
> SNOW-232777 Subclass-ed HTTPAdapter to add the header to proxy headers

- DESCRIPTION.rst
- src/snowflake/connector/network.py
- src/snowflake/connector/version.py
…s (#599)
* Subclass-ed HTTPAdapter to add the header to proxy headers
> Bumped up PythonConnector PATCH version from 2.3.8 to 2.3.9

- setup.py
This PR removes the upper version pin of `pytz`, as this library doesn't follow semantic versioning I don't see a reason to maintain an upper pin. Secondly it has not broken testing yet, so I'm going to give it the benefit of the doubt and remove the upper pin until it breaks something in our testing pipeline.
> SNOW-274851 removing pytz pin as it doesn't follow semver anyway

- .github/workflows/build_test.yml
- Jenkinsfile
- ci/build_darwin.sh
- ci/build_docker.sh
- ci/build_linux.sh
- ci/build_windows.bat
- ci/docker/connector_build/Dockerfile
- ci/docker/connector_test/Dockerfile
- ci/set_base_image.sh
- ci/test_darwin.sh
- ci/test_docker.sh
- ci/test_linux.sh
- pyproject.toml
- setup.py
- tox.ini
SNOW-240336
Adding support and testing for Python 3.9 for both Jenkins and GH actions.
`pyarrow` dropped releasing `manylinux1` wheels, so I did some digging and it appears as it's okay for us to do the same as well.
> SNOW-240336 adding Python 3.9 support

- src/snowflake/connector/network.py
The previous code changes raises an exception when client receives "log received" confirmation from telemetry because `ret['data']` is a str in this case, the exception is caught by upper level try clause.
This fix adds a type check to avoid the exception.
> Add bug fix for SNOW-266042 Improve Query/Request ID logging

- setup.py
- src/snowflake/connector/__init__.py
- src/snowflake/connector/azure_util.py
- src/snowflake/connector/compat.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/errors.py
- src/snowflake/connector/file_compression_type.py
- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/gcs_util.py
- src/snowflake/connector/local_util.py
- src/snowflake/connector/network.py
- src/snowflake/connector/remote_storage_util.py
- src/snowflake/connector/s3_util.py
- test/integ/test_dbapi.py
- test/integ/test_large_put.py
- test/integ/test_put_get_medium.py
- test/unit/test_gcs_util.py
- test/unit/test_s3_util.py
Adds support for the upcoming `THRESHOLD` keyword in `PUT` statements. While adding this I found that file metadatas were these very dynamic dictionaries, so it was pretty complicated to see where they went when I added them. So I well-defined them with `dataclasses`.
I also did some smaller code cleanups, like updated logging messages, and changed around some class names to be PEP-8 compliant.
> SNOW-136583 adding multipart PUT threshold support

- setup.py
- tox.ini
[SNOW-292477](https://snowflakecomputing.atlassian.net/browse/SNOW-292477?atlOrigin=eyJpIjoiOWY1N2U2YTE4ZjU4NDAxODk1OGZlZDJlMzA5ODU1MDQiLCJwIjoiaiJ9)
Enabled by the pytest plugin `pytest-xdist`, specifying `pytest -n auto`  detects the number of CPU's (denoted `x`) and run tests in parallel  using `x` processes.
> SNOW-292477 Add pytest-xdist dependency and -n auto option

- DESCRIPTION.rst
- src/snowflake/connector/version.py
> SNOW-294004: Bumped up PythonConnector MINOR version from 2.3.10 to 2.4.0

- src/snowflake/connector/auth.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/converter.py
- src/snowflake/connector/cursor.py
- test/integ/test_connection.py
SNOW-294266
The implicit commit in `SnowflakeConnection.__exit__` is causing mayhem when the session parameter `autocommit` is set to true. This PR makes the connection object `rollback`/`commit` upon closure only if `autocommit` is turned off, or is missing.
> SNOW-294266 make connection object exit autocommit aware

- DESCRIPTION.rst
- src/snowflake/connector/version.py
* SNOW-295621: Bumped up PythonConnector PATCH version from 2.4.0 to 2.4.1
> Snow 295621 python connector version bump (#643)

- .pre-commit-config.yaml
- ci/change_snowflake_test_pwd.py
- setup.py
- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/ocsp_asn1crypto.py
- src/snowflake/connector/ocsp_snowflake.py
- test/conftest.py
- test/integ/pandas/test_unit_arrow_chunk_iterator.py
- test/integ/pandas/test_unit_arrow_result.py
- test/integ/sso/test_connection_manual.py
- test/integ/test_client_session_keep_alive.py
- test/integ/test_concurrent_create_objects.py
- test/integ/test_concurrent_insert.py
- test/integ/test_connection.py
- test/integ/test_cursor.py
- test/integ/test_load_unload.py
- test/integ/test_put_get_medium.py
- test/integ/test_put_get_user_stage.py
- test/integ/test_put_get_with_gcp_account.py
- test/integ/test_qmark.py
- test/integ/test_query_cancelling.py
- test/integ/test_session_parameters.py
- test/integ/test_statement_parameter_binding.py
- test/unit/test_ocsp.py
- test/unit/test_s3_util.py
apologies for the drive-by, was looking at this repo for another reason
- pre-commit only runs on checked-in files, so I fixed `exclude`
- `seed-isort-config` is unnecessary for isort >= 5
- upgraded all the hooks
- `flake8` has its own pre-commit config now (and is removed from
pre-commit/pre-commit-hooks)
you might also be interested in https://pre-commit.ci :)
> SNOW-298303 improve .pre-commit-config.yaml

- src/snowflake/connector/connection.py
- test/integ/test_session_parameters.py
This reverts the client session keep alive fix.  This will be put back in after the preannouncement.
> reverted SNOW-264606 client session keep alive fix

- setup.py
- src/snowflake/connector/arrow_iterator.pyx
- src/snowflake/connector/arrow_result.pyx
- src/snowflake/connector/connection.py
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.hpp
- src/snowflake/connector/cursor.py
- test/integ/pandas/test_arrow_pandas.py
- test/integ/pandas/test_unit_arrow_chunk_iterator.py
SNOW-302368
This PR adds a way to turn `NUMBER` columns into `decimal.Decimal` when retrieved to keep infinite precision while using Arrow. When compared to #668 I needed to turn the function argument into a connection parameter, because of the case when Arrow is used automatically by the back-end then there's no way to pass an argument to the `__next__` function of the iterator through the results.
While I don't exactly like putting all options as connection parameters I think we should rework our setting system to have most of them configurable on all of the following levels:
* connection
* cursor
* statement (execution)
I have filed myself the following ticket SNOW-302368 to come up with a good system for adding and handling these settings on all 3 of these levels at the same time.
> SNOW-302368 new Arrow NUMBER to Decimal converter option

- .github/workflows/build_test.yml
- test/integ/test_put_get_user_stage.py
SNOW-351142
Hotfixing `fix_lint` step for GH actions, it also fixes a linting issue in `master`, but to see it skipping beforehand see this example: https://github.com/snowflakedb/snowflake-connector-python/runs/2460860144?check_suite_focus=true and the run on this PR
> SNOW-351142 explicitly set python version to 3.6 for fix_lint

- src/snowflake/connector/arrow_iterator.pyx
- src/snowflake/connector/constants.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_batch.py
- src/snowflake/connector/result_set.py
- test/integ/pandas/test_arrow_pandas.py
SNOW-296993
SnowSQL doesn't have access to our compiled code, so the following import statement broke SnowSQL build:
https://github.com/snowflakedb/snowflake-connector-python/blob/d7fd76a55b5b768f3e8113afb2574b3b843d5679/src/snowflake/connector/result_batch.py#L26
This PR fixes this issue. To observe the issue please see: http://172.16.20.10:8080/job/Snowsql-Mac64-Test/2605/console
I'll try to see if I could run this test before I flip the review to be ready on this branch
> SNOW-296993 fixing import statement for SnowSQL

- src/snowflake/connector/result_set.py
- src/snowflake/connector/telemetry.py
- test/conftest.py
- test/integ/test_cursor.py
SNOW-296993
SnowSQL builds have been broken since Friday because the telemetry `_first_chunk_time` is not always recorded.
This PR skips reporting that Telemetry when it needs to and it also introduces a fixture that we can use to easily capture Telemetry messages during testing (it can also be used to disable telemetry by not propagating the messages to the real telemetry objects).
> SNOW-296993 fixing a ResultBatch telemetry bug

- .github/workflows/build_test.yml
SNOW-353595
It looks like `auditwheel` now tags the same wheel with multiple tags instead of creating multiple wheel files tagged for one specific `manylinux` version.
> SNOW-353595 updating build and test pipeline

- ci/test_linux.sh
SNOW-256036
Tests seem to have started hanging again. While we get around to investigate what's causing the hanging on Jenkins let's disable parallel test runs.
> SNOW-256036 disable parallel unit test runs on Jenkins

- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
This PR addresses changes requested in https://snowflakecomputing.atlassian.net/browse/SNOW-344429.
I followed Mark's suggestion of adding a generator function that takes an argument - allowing the user to set `quote_identifiers` as they wish. The docstring in the PR shows an example of how to use the new generator function.
The generator function uses `partial` to create a function with `quote_identifiers` set.
The test for this function can be found at: https://github.com/snowflakedb/snowflake/pull/28037
The test written passes precommit, as can be seen here: https://ci75.int.snowflakecomputing.com/job/RT-Precommit/974/
> [SNOW-344429] Adds make_pd_writer

- src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp
- test/integ/test_cursor.py
SNOW-303685
Fixing segfault error when using `DictCursor` with Arrow result format
> SNOW-303685 fixing segfault when using DictCursor and arrow result format

- src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp
- src/snowflake/connector/cpp/ArrowIterator/IColumnConverter.hpp
This PR addresses changes requested in [SNOW-169178](https://snowflakecomputing.atlassian.net/browse/SNOW-169178).
Replaces raw PyObject*s with UniqueRefs (a wrapper for PyObject*). When the local variable goes out of scope, the destructor of UniqueRef is called, ultimately calling XDECREF on the pointer.
Verified that memory leaks are not happening using sample code: https://gist.github.com/schitlurharidas/25b66e6220923597fb019bffaf6749a5
> SNOW-169178 Replace pointers with UniqueRefs

- src/snowflake/connector/auth_keypair.py
- test/integ/test_key_pair_authentication.py
Replacing '-' with '_' has led to a problem with certain accounts. Removing this logic so as to not break existing customers.
> SNOW-364567 SNOW-303944 Remove substitution of dash for underscore in account names

- src/snowflake/connector/cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/cpp/ArrowIterator/CArrowTableIterator.cpp
Address changes in: https://snowflakecomputing.atlassian.net/browse/SNOW-365904
Old code was implicitly using `UniqueRef(UniqueRef&& other)` which was made to be `explicit`
> SNOW-365904 Intialize UniqueRefs without move operator

- setup.py
SNOW-362198
We hit an issue when the first release of `certifi` in 2021 was released, in a very quick attempt to fix our internal pipelines I bumped the upper limit for it.
Now I believe that was a mistake and we should not have any upper limit for dependencies such as `certifi`.
Closes #732
> SNOW-362198 removing upper certifi pin

- src/snowflake/connector/auth_keypair.py
- test/integ/test_key_pair_authentication.py
SNOW-365900
This fixes the issue of JWT tokens being invalid for account aliases with dashes in them, and runs a test against one of these accounts with an org alias in QA. The current Jenkins credentials running against a dev deployment would require us to set up org/account creation with every Jenkins run, so it seems more feasible to test against an org that doesn't have to be re-created each run.
> SNOW-365900 Test key/pair authentication with regionless URL

- src/snowflake/connector/arrow_iterator.pyx
- src/snowflake/connector/constants.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_batch.py
- src/snowflake/connector/result_set.py
- src/snowflake/connector/telemetry.py
- test/integ/pandas/test_arrow_pandas.py
- test/integ/pandas/test_unit_arrow_chunk_iterator.py
- test/integ/test_cursor.py
This PR addresses changes requested in: SNOW-177082
To summarize the changes:
- the existing `ROW_UNIT` and `TABLE_UNIT` constants are replaced with an Enum. All usages of these constants are also replaced. In `arrow_iterator.pyx` I made sure to use the .value of the Enum to allow for string comparison
- `cursor.py` has 2 new functions, `fetch_arrow_batches()` and `fetch_arrow_all()`, which use the corresponding `result_set.py` function
- `result_set.py` no longer converts pyarrow.Tables to dataframes. Instead, `result_batch.py` will return a pyarrow.Table/dataframe where appropriate. This is specified by a keyword argument.
- `result_batch.py`:
- added two new methods called `to_arrow` and `to_pandas`. These are implemented only by the `ArrowResultBatch`
- moved the existing …
> SNOW-177082 Adds `to_arrow` and `to_pandas`, refactors `result_set` and `result_batch`

- src/snowflake/connector/arrow_iterator.pyx
- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_batch.py
- src/snowflake/connector/result_set.py
- test/integ/test_cursor.py
This PR addresses changes requested in  https://snowflakecomputing.atlassian.net/browse/SNOW-361357
It passes the cursor's description list to each of the result batches, and can be accessed by each individual batch with `.schema`.
The added test has an example of the usage for this function
> SNOW-361357 Provide interface exposing `schema` info to `ResultBatches`

- README.rst
thought it'd make sense to drop this line given that this library has a sizable chunk of C now.
> SNOW-373625 remove five-year-old line from README

- src/snowflake/connector/s3_util.py
Skip logging meta data from AWS as it might contain sensitive information. This is a temporary fix to for the problem. A more holistic approach is being explored which might take a little longer.
> Remove offending log line.

- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
SNOW-299658
**Behavior change** to quote column names properly in `snowflake.connector.pandas_tools.write_pandas` when `quote_identifiers=True`.
Closes #745
> SNOW-299658 quote column names in write_pandas when quote_identifiers is True

- src/snowflake/connector/network.py
- src/snowflake/connector/result_batch.py
- test/helpers.py
- test/integ/test_cursor.py
- test/unit/test_result_batch.py
This PR addresses changes requested in: [SNOW-361210](https://snowflakecomputing.atlassian.net/browse/SNOW-361210).
The core functionality for retries was already there, but there were a few differences between this and the old `ChunkDownloader` error handling. See [this comment](https://snowflakecomputing.atlassian.net/browse/SNOW-361210?focusedCommentId=1683481) for more details. In short, the old code didn't log/raise retry errors quite correctly, and accepted status codes other than 200 which this PR addresses.
I also added quite a few unit tests to verify that retries are working as we expect.
> SNOW-361210 Adds Retry Logic and Tests

- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
Before this change, if we run `cursor.describe("insert into ...")` (or `delete ...`), an "out of index" error will be returned because `data['rowset']` is empty, in `_init_result_and_meta` method in `cursor.py`. This PR fixes this bug and adds a corresponding test.
> SNOW-361263: Fix describe method when running `insert into ...`

- DESCRIPTION.rst
- src/snowflake/connector/version.py
> SNOW-394801: Bumped up PythonConnector MINOR version from 2.4.6 to 2.5.0

- Jenkinsfile
SNOW-359246
run semgrep in temp dir to prevent potential issue of .git folder ownership being changed to root
also use new baseline ref parameter to stop reporting issue in upstream branch since current branch was created
> SNOW-359246 run semgrep in temp dir and use new baseline ref

- src/snowflake/connector/file_transfer_agent.py
Description
Use s3 Regional URL information communicated from GS gets lost while executing actual PUT command. The driver instead of using the s3 regional URL uses the default S3 URL. This has the potential to go unnoticed in any environment where the S3 default URL has not been blocked. For the same reason, this problem happens consistently in Privatelink env where the default S3 URL is unavailable.
The issue happens because use_s3_regional_url information is not correctly in the upload client class object
> SNOW-378268 Python connector S3 PUT Failure Fix

- src/snowflake/connector/result_batch.py
- src/snowflake/connector/result_set.py
- test/integ/pandas/test_arrow_pandas.py
- test/integ/test_cursor.py
- test/unit/test_result_batch.py
This PR addresses changes requested in [SNOW-361211](https://snowflakecomputing.atlassian.net/browse/SNOW-361211).
It adds the ability for a ResultBatch to make requests with an existing session if supplied. 
The ResultSet iterator will supply its connection when creating each ResultBatch iterator. This way, when iterating through all batches (either via a fetchall/fetch_pandas_all/fetch_arrow_all), sessions are reused at the download step.
To support this, ResultBatches have a new `_use_session` attribute that gets set to True by the ResultSet. The ResultSet also passes in `self._connection` to the ResultBatch create_iter.
> SNOW-361211 Allow ResultBatches to use existing Sessions

- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_batch.py
- src/snowflake/connector/result_set.py
- test/integ/test_cursor.py
- test/unit/test_result_batch.py
1. What JIRA issue is this PR adressing? Make sure that there is an accompanying issue to your PR.
Fixes [SNOW-361211](https://snowflakecomputing.atlassian.net/browse/SNOW-361211) with what should be the final performance-related bug. See performance runs 7903, 7911 on the ClientPerfs Dashboard.
-  logging when `_parse` is invoked.
This changes the `_get_pandas_iter` function to return an iterator rather than have it be a generator. Since it must return 
an iterator, when `create_iter` is submitted to the TPE, the download will happen. 
Likewise, JSONResultBatch's `_parse` function is changed to return a list rather than be a generator (and hence parsing 
happens when the function is …
> SNOW-414845 Fix Pandas and JSON Parallel Fetch

- .github/workflows/build_test.yml
- ci/build_darwin.sh
Fixes SNOW-424556
Bumping the Mac OSX target version to `10.14` as we dropped support for `10.13`.
> SNOW-424556 bump macosx target version

- src/snowflake/connector/result_batch.py
Fixes SNOW-430464
Ever since we merged https://github.com/snowflakedb/snowflake-connector-python/commit/740d9b9003ca8c0adee77628dce85d981919e66f our performance tests have been failing on Azure.
I tracked the issue down to https://github.com/snowflakedb/snowflake-connector-python/blob/740d9b9003ca8c0adee77628dce85d981919e66f/src/snowflake/connector/result_batch.py#L324 not retrying as it should have.
When I dove into the diff between the old `chunk_downloader` code I found the same retry logic here: …
> SNOW-430464 rework stream request get to process all the response at request time

- src/snowflake/connector/connection.py
- src/snowflake/connector/converter.py
- src/snowflake/connector/sfbinaryformat.py
- test/integ/test_cursor.py
This PR addresses changes requested in [SNOW-368531](https://snowflakecomputing.atlassian.net/browse/SNOW-368531)/ [GH Issue](https://github.com/snowflakedb/snowflake-connector-python/issues/750).
Our behavior when resolving the "type" of value had a bug. The best way to illustrate this would be with an example.
When using `executemany` to insert values, you would use a command such as this:
```python
cursor.executemany(
'INSERT INTO date_test (birth_date) values (?)',
[[datetime.date(1969, 2, 7)],[datetime.date(1969, 1, 1)]]
)
```
The `executemany` function would then transform the values in to a list like this ([see this](https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/cursor.py#L985)) :
```python 
[ datetime.date(1969, 2, 7), …
```
> SNOW-368531 Fix `executemany` insert qmarks behaviour

- setup.py
Fixes SNOW-452162
`use_2to3` was deprecated yesterday by `setuptools` https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v5802 , removing this option now
> SNOW-452162 remove deprecated setuptools option

- src/snowflake/connector/result_batch.py
Fixes SNOW-446950
The newest release has a bug where the else clause of the modified if-then clause gets triggered when `rowset_b64` because empty string evaluates as `False`. This fixes the bug, so that the else clause shouldn't be triggered.
> SNOW-446950 default value bugfix

- src/snowflake/connector/time_util.py
Fixes #836 
This marks non-critical HeartBeatTimer threads as daemon threads (threads that should not keep the Python process from exiting while they are running).
> SNOW-436322 mark HeartBeatTimer threads as daemon threads

- src/snowflake/connector/pandas_tools.py
Fixes #438
For some reason in some cases `COPY INTO <table>` returns the number of rows inserted as a string, this forces those strings to be casted into integers.
I was unable to reproduce the issue, but I don't think that adding this extra cast would detrimental for the Python connector.
> SNOW-200089 expicitly cast a column into integer in write_pandas

- src/snowflake/connector/storage_client.py
- test/integ/test_put_get.py
Fixes SNOW-466099
I made a bug, where before downloading a file we performed a HEAD on that remote file, when generating the url to perform the HEAD on I attached the name of the file instead of the url instead of the full path.
As an example consider that we wanted to reach: `snowflakes-super-secret-customer-stage.s3.amazonaws.com/u8er7-s-afdas3255/stages/ae0c05e7-29a3-47frg-9555-35cssfde8787/sub/folders/test.csv`, we instead generated: `snowflakes-super-secret-customer-stage.s3.amazonaws.com/u8er7-s-afdas325 …
> SNOW-466099 fixed remote file HEAD bug

- setup.py
Fixes SNOW-487250
This build flag was added back in the day for what I think was a workaround for the really old compiler we internally used.
This flag has been causing issues to some of our customers, who are using Anaconda.
In this PR I want to remove it as it doesn't seem necessary anymore.
> SNOW-487250 remove D_GLIBCXX_USE_CXX11_ABI

- src/snowflake/connector/connection.py
- src/snowflake/connector/constants.py
Fixes SNOW-493094
This PR is removing a now useless connection parameter `s3_connection_pool_size`
> SNOW-493094 removing s3_connection_pool_size connection parameter

- .github/workflows/build_test.yml
Fixes SNOW-496488
When I updated our build procedure the last time `build` was very new, but since then I have seen many open-source projects use it, so now I'm sure that the community has committed to this library. So in this PR I'm switching us to use `build` for builds.
> SNOW-496488 switching to using build for building wheels and sdists

- src/snowflake/connector/s3_storage_client.py
- test/integ/test_put_get.py
Fixes SNOW-480963
In SDKless implementation, when file name is something like `data~%23.gz`, this will be encoded to `data%7%2523.gz` into request URL. This is different than old implementation, in which S3 SDK uses a different "safe" parameter `quote(url, safe="/~")` and encodes the URL into `data~%2523.gz`. Without this fix, customers will receive 403  error when they try to PUT a file name that contains "~".
> SNOW-480963: URL quote for s3 has to use "safe=" identical to boto lib

- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/storage_client.py
- test/integ/test_put_get.py
Fixes #909 SNOW-487478
The issue is perfectly described in #909 the `BytesIO` context manager closes the file and so multipart streaming puts haven't worked since we switched to the SDKless PUT/GET. Here I abandon using the context manager and manually close the stream in case of us opening a new one.
> SNOW-487478 streaming multipart upload

- src/snowflake/connector/auth_webbrowser.py
Fixes #303
By allowing users to specify their socket port and address, we can use this from within containers running DBT with SSO authentication.
Example compose configuration:
```
version: "3.8"
services:
dbt:
image: some-magic-dbt-image
environment:
SF_AUTH_SOCKET_ADDR: 0.0.0.0
SF_AUTH_SOCKET_PORT: 8080
BROWSER: /bin/echo
ports:
- 8080:8080
volumes:
- ~/.dbt:/root/.dbt # Mount your DBT profile
- ./:/usr/app # Mount your app
- ~/.cache/snowflake:/root/.cache/snowflake # Mount cache so it does not ask again
```
This also leverages the clever trick in …
> SNOW-157438 Allow web authenticator to select its listening port and address

- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
Relates to #961 SNOW-501058 and SNOW-513807
When we merged #962 I didn't catch that it was a behavior change, which led to some of our internal tests being broken.
This PR introduces a connection parameter that switches between old and new behaviors. Will be following up with a behavior change announcement and switching the default value as soon as possible.
> SNOW-501058 adding connection parameter to protect behavior change

- setup.py
Fixes SNOW-521102
By specifying the description content type our PyPi description should render correctly once again.
> SNOW-521102 fix long description rendering for PyPi

- .gitignore
- .pre-commit-config.yaml
- MANIFEST.in
- setup.py
Fixes SNOW-510552
Updating `setup.py` to only use `MANIFEST.in` for tracking data files ([documentation](https://setuptools.pypa.io/en/latest/userguide/datafiles.html)). This means that from now on we won't have to track data files in `setup.py` anymore.
Overall this should lead to less bugs and also fix the issue where `py.typed` was not included in wheels even thought it was in the `package_data` dictionary.
I also fixed another bug that causes our description on PyPi to not render correctly.
> SNOW-510552 fix py.typed not being included in wheels

- src/snowflake/connector/auth.py
- test/unit/test_auth.py
Fixes SNOW-514815
There's a bug, where if a customer enrolls into DUO MFA with a "tablet" (which means that no sms authentication is available) this is not handled correctly by the connector.
I've modified an already existing test and verified the fix manually.
> SNOW-514815 handling no sms case for DUO

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
- setup.py
Fixes SNOW-507544
Many open-source Python project switched to using `setup.cfg` instead of `setup.py`.
We should also start transitioning towards using it in case support of `setup.py` winds down.
> SNOW-507544 shifted package metadata from setup.py to setup.cfg

- src/snowflake/connector/cursor.py
- src/snowflake/connector/telemetry.py
Fixes SNOW-526691
This is just adding extra telemetry that we'd like to collect before switching the default value of of the connection parameter `interpolate_empty_sequences`. Relates to #993
> SNOW-526691 adding new telemetry reporting

- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
SNOW-347580: Auto-create tables for a pandas dataframe that is passed to write_pandas
Updated write_pandas tests to also do a run where tables are auto-created. Also added tests for auto-created tables with quoted names
Fixes #686 
Adds the ability to auto-create a table when using write_pandas
> SNOW-347580: Auto-create tables for a pandas dataframe that is passed to write_pandas

- src/snowflake/connector/constants.py
- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
Description
Added support for geoJson to show up as GEOGRAPHY when enabled
Testing
Added testing for when it is disabled and enabled
Fixes SNOW-499804
Recognizes geoJson as a GEOGRAPHY type in the connector
> SNOW-499804 Add Geography Types

- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
> SNOW-499496 Fix Cursor.executemany() crash if args is empty or an iterator

- src/snowflake/connector/connection.py
- src/snowflake/connector/constants.py
- test/unit/test_connection.py
SNOW-533748
This is an enhancement to the python connector to allow snowflake to track partner driven consumption by searching for a partner defined environment variable in circumstances where a partner provides managed infrastructure, but a customer manual downloads the connector via pip.
> SNOW-533748 partner application name injection

- src/snowflake/connector/auth_webbrowser.py
- test/unit/test_auth_webbrowser.py
Fixes #303
PR #847 only added printing of the SSO URL however that is not enough when you depend on the response or in this case the URL you are redirected to as part of the SSO Authentication. This PR waits for the user to copy/paste the URL they are redirected to and extracts the token from it.
I can now use Snowflake from Google Colab by installing from my branch
```
pip install "https://github.com/iserko/snowflake-connector-python/archive/refs/heads/SNOW-XXXXXX_wait_for_url_input_after_sso.zip#egg=snowflak …
```
> Wait for URL input after SSO login

- src/snowflake/connector/result_set.py
- test/integ/pandas/test_arrow_pandas.py
- test/integ/test_cursor.py
Fixes SNOW-544463
The `fetch_pandas_all` function does not put nice index numbers into the resulting `pandas.DataFrame` it produces, This PR fixes this and adds a test to verify this behavior in the future.
> SNOW-544463 fix index numbers when using fetch_pandas_all

- DESCRIPTION.md
- setup.cfg
- src/snowflake/connector/version.py
Fixes SNOW-560944
The release `2.7.5` released today broke support for Python 3.6 and the `python_requires` tag was in an incorrect position. I have now manually tested that this will correctly fail to install on Python 3.6.
This PR also has all the release stuff in it for a new release.
> SNOW-560944 fix python_requires tag from setup.cfg

- .github/workflows/build_test.yml
- pyproject.toml
Fixes SNOW-572600
Switching to `cibuildwheel` to build wheels with. This switch allows us to build ARM wheels for both Linux and MacOS.
> SNOW-572600 switch to new build process

- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/network.py
- test/unit/test_retry_network.py
Fixes [SNOW-469340](https://github.com/snowflakedb/snowflake-connector-python/issues/878)
This makes it possible to pass a `no_retry=True` parameter to the `execute_async` outer method to allow the user to skip the retries done by the connector and return the error to the user. The underlying `_post_request` method in `network.py` already had a parameter `no_retry`. The change only propagates that parameter from the upper methods down to that `_post_request` method and in case set to `True` it returns an …
> SNOW-469340 add _no_retry option when submitting queries

- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_batch.py
- test/integ/test_cursor.py
Fixes SNOW-584166
Our optional dependency is `pandas` but the error message shows `pyarrow`. This PR fixes this error message.
> SNOW-584166: Fix the error message when pandas is not installed 

- setup.cfg
When browsing PyPI, I'm expecting a documentation page to be specific to the package, not a general page about the related platform. If one needs access to generic Snowflake doc, it is one click away from the Python Conncetor's Doc. Pointing directly to the Python Conncetor's Documentation feels more natural.
If this is against your guidelines, or there's any other objection, just reject the PR.
> Update documentation link to python specific main page

- src/snowflake/connector/connection.py
- test/unit/test_connection.py
https://snowflakecomputing.atlassian.net/browse/DATA-1339
In order to correctly attribute connector usage to streamlit, check sys.modules for the presence of "streamlit" and if found, and not set otherwise, use that to set the application appropriately.
> DATA-1339 Set application name based on streamlit being in sys.modules

- ci/test_docker.sh
- ci/test_fips_docker.sh
- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/s3_storage_client.py
- test/integ/test_put_get_user_stage.py
- test/unit/test_s3_util.py
A test is added to make sure right endpoint is used according to accelerate configuration
Fixes SNOW-507942
1)  Check s3 accelerate config to use right URL; 2) parse XML response to retrieve configuration status correctly; 3) make sure the accelerate config could be updated correctly from previous s3 API call to all s3 client objects where they have their own endpoint.
I have read the CLA Document and I hereby sign the CLA
> SNOW-507942 handle s3 accelerate configuration correctly

- src/snowflake/connector/azure_storage_client.py
- src/snowflake/connector/encryption_util.py
- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/gcs_storage_client.py
- src/snowflake/connector/s3_storage_client.py
- src/snowflake/connector/storage_client.py
- test/integ/test_put_get_compress_enc.py
- test/unit/test_encryption_util.py
when content-encoding header of download response is set to 'gzip', urllib3 decompression on fly was
triggered and failed on encrypted data. This is not backward compatible with previous behavior.
Integrated Test added to mock the scenario when Content-Encoding=gzip is added
which is the case when PUT by JDBC.
Fixes #NNNN
> SNOW-522489 Ignore content-encoding when GET

- test/conftest.py
Fixes #NNNN
A recently added test exposed an issue where the `internal` test tag didn't work as expected. It turns out that Our Mac and Windows tests also use public Snowflake deployments, so these runs should also skip running `internal` tests.
Now correct runs:
- https://jenkins.int.snowflakecomputing.com/view/ClientMasterJobs/job/RT-PyConnector37-Win/460/
- https://jenkins.int.snowflakecomputing.com/view/ClientMasterJobs/job/RT-PyConnector38-Win/351/
- …
> fix skip logic

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- test/integ/test_async.py
Fixes SNOW-584369
Errors raised when running `get_results_from_sfqid` are missing `errno` numbers. In addition I found that we had no nice error messages when a query is not found by the same method. So I added error checking and nicer error message when this happens.
> SNOW-584369 get_results_from_sfqid missing errno

- DESCRIPTION.md
- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
Fixes #1175 
Using the [write_pandas()](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.Session.write_pandas) API there is now a way to optionally overwrite contents of a Snowflake table with that of a Pandas DataFrame.
> SNOW-617426 added overwrite option to write_pandas

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
- test/unit/test_cursor.py
Fixes SNOW-629080
Snowflake doesn't support lastrowid, according to [PEP249](https://peps.python.org/pep-0249/#lastrowid), we should return None for this attribute.
```definition in pep249
Cursor.lastrowid
This read-only attribute provides the rowid of the last modified row 
(most databases return a rowid only when a single INSERT operation is performed).
If the operation does not set a rowid or if the database does not support rowids,
this attribute should be set to None.
The semantics of .lastrowid are …
```
> SNOW-629080: investigate and implement lastrowid

- DESCRIPTION.md
- setup.cfg
- src/snowflake/connector/cache.py
- src/snowflake/connector/ocsp_snowflake.py
- test/integ/test_connection.py
- test/unit/test_cache.py
- test/unit/test_ocsp.py
Fixes SNOW-611961
In this PR I add an extension of #1195 that adds file caching on top of in-memory caches.
On every write to the in-memory cache (`__setitem__`, `update`) we generate a random number 0-9 and if it's 1 then we save to disk. This is done so if multi-processing starts multiple connectors with no cache available we distribute their writes randomly. The only other time we try to save is during tear-down.
One caveat of save is that we try to acquire the …
> SNOW-611961 in-file cache implementation

- src/snowflake/connector/cursor.py
Fixes SNOW-651560
`extTypeName` can exist in the  returned json result but it can be empty when it's returned from table stored proc. See the jira for more details and the code path. After it's merged, I will update the SP connector as well.
> SNOW-651560: Fix the metadata issue when `extTypeName` from the returned json result is empty

- src/snowflake/connector/__init__.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/telemetry.py
- test/integ/test_connection.py
SNOW-644849
We would like to know what packages are imported at Python runtime along with connector, which can help us understand the user scenarios of python connector. The message will looks like this:
```
{
"source": "PythonSnowpark",
"type": "client_imported_packages",
"value": "{'pdb', 'bz2', 'abc', 'ssl', 'faulthandler', 'fnmatch', 'pytest', 'shlex', 'fractions', 'enum', 'queue', 'certifi', 'traceback', 'pprint', 'pwd', 'pickle', 'ast', 'uu', 'pkg_resources', 'codecs', 'gc', 'hmac', 'copy', 'errno', …
```
> SNOW-644849: Add telemetry about imported pacakages at runtime

- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
Fixes [SNOW-460809 Improve logging to log explicit how many rows were embedded in the Snowflake query response](https://snowflakecomputing.atlassian.net/browse/SNOW-460809)
Added `INFO` level logging message in `_init_result_and_meta` to retrieve the first chunk's rowcount if the query was not `is_dml` or `is_file_transfer`
> SNOW-460809 Attempt to add INFO level logging message regarding first chunk rowcount

- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
[SNOW-364424: Support for providing kwargs to to_parquet when using write_pandas](https://snowflakecomputing.atlassian.net/browse/SNOW-364424)
- It's a small 2 line change. The use of `**kwargs` in the `df.to_parquet` function seems very niche so if we could get some idea of how the customer uses the functionality, I could write a test for it. Just as a sanity check, does the user just want access to the non-exposed parameters of `to_parquet` (including `engine`, `index`, `partition_cols`, `storage_options`), or actually `**kwargs`?
4. Please describe how your code solves the related issue.
Added `**kwargs` to `write_pandas` arguments and …
> SNOW-364424: Exposed to_parquet kwargs parameter in write_pandas

- .github/workflows/build_test.yml
- ci/test_fips.sh
- setup.cfg
- tox.ini
Description
This version bump is to avoid version conflict with pyOpenSSL
Testing
Added a new workflow test to run pip-compile
Fixes #1265 
Bumping `cryptography` to `<39.0.0` makes it compatible with `pyOpenSSL` that requires `>=38.0.0`
> SNOW-669945 Bump cryptography version to <39.0.0

- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- test/integ/test_async.py
Fixes #SNOW-657710
Parallelize the status checks by running all the GET requests in a ThreadPoolExecutor.
> SNOW-657710 Parallelize async query status check when closing connection

- .pre-commit-config.yaml
- src/snowflake/connector/test_util.py
Description
test_util is supposed to only be used by snowflake regression test, but currently it runs for all Jenkins linux hosts, which is not desired. A quick fix is to also check CLIENT_LOG_DIR_PATH_DOCKER, which presumbly is not used by most customers if not all.
Testing
existing tests
Fixes #NNNN
> SNOW-680774 Check CLIENT_LOG_DIR_PATH_DOCKER for ENABLE_TELEMETRY_LOG

- test/integ/test_errors.py
Fixes broken test from 1297
Forgot to update regex, regex is now updated
> SNOW-535152 Updated regex to also include the old error code

- ci/test_fips.sh
Fixes SNOW-688750
hey @sfc-gh-mkeller , is there a reason we pin the cryptography to 3.x. and build in FIPS test? I found unpinning the version could resolve the FIPS issue. If there's no specific reason, then we could unpin it.
however, I'm still not sure about the root cause, maybe it's as you said -- the ocsp responder has changed the hash algorithm, which is not supported by the older version cryptograph.
> SNOW-688750: OCSP test failure in FIPS mode

- src/snowflake/connector/storage_client.py
> SNOW-686222: Remove os.path.realpath in storage_client.py

- src/snowflake/connector/cache.py
- src/snowflake/connector/ocsp_snowflake.py
Fixes SNOW-668660
Reduce the number of lock and writing operations when parsing the `ocsp_response_cache.json`.
`ocsp_response_cache.json` contains nearly ~200 items, previously we perform at least 2 times of lock acquisition/release on each item for finding/deleting/updating cache.
This is unnecessary and could be optimized by batching the operations -- we acquire the lock at the beginning, then updating all the entries, then release the lock and write the cache back to file.
> SNOW-668660: Inefficient file lock for OCSP cache mechanism

- DESCRIPTION.md
- src/snowflake/connector/_sql_util.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/gcs_storage_client.py
- test/unit/test_cursor.py
Fixes SNOW-693548
This fixes the CVE https://nvd.nist.gov/vuln/detail/CVE-2022-42965
The issue comes from the greediness of the original regex. With this reworked function we have roughly linear performance. This is achieved by starting from the beginning to lazily strip away comments one-by-one instead of matching the whole SQL command with one regex. The new SQL is also better by matching more than multi-line comments.
> SNOW-693548 fixing redos attack

- DESCRIPTION.md
- src/snowflake/connector/encryption_util.py
- test/integ/test_put_get.py
Fixes #SNOW-676736
mkstemp creates a temporary file in the most secure manner possible -- which is only given permission to the current user, not to `group` or `other` which is not expected.
change to use `open` which will inherit the default file permission.
> SNOW-676736: get file results in change of file permissions does not inherit parent folder permission

- DESCRIPTION.md
- setup.cfg
- tox.ini
Fixes #SNOW-679732
cryptography has its own [API stability policy](https://cryptography.io/en/stable/api-stability/#deprecation) which is different from the semantic versioning, however, we have customers who like to catch up with the latest cryptography release for security fix, avoid dependency conflict etc.
As a compromise, we decide to loosen the upper bound of cryptography pin to +3 version as per their API stability policy.
The major reasoning for pinning the version is that customer will pin the …
> SNOW-679732: loosen cryptography restriction

- DESCRIPTION.md
- src/snowflake/connector/cache.py
- src/snowflake/connector/ocsp_snowflake.py
- src/snowflake/connector/version.py
- test/unit/test_cache.py
Fixes SNOW-698526
`_getitem` should not be overwritten in SFDictFileCache as `_getitem` is used by load to clean up in-memory expired cache. To resolve the issue, introduce a new non-locking get method in SFDictFileCache to segregate the functionality
> SNOW-698526: Python connector 2.8.2 infinite loop in OCSP cache validation

- .github/workflows/build_test.yml
- test/extras/README.md
- test/extras/__init__.py
- test/extras/run.py
- test/extras/simple_select1.py
- tox.ini
Fixes SNOW-706773
In this PR I add back `extras` tests (originally added in #380 and then removed in #981 ), the only one of which will now test that we can simply log into Snowflake and execute `select 1;`. This should catch adding dangling import statements that aren't dependencies.
> SNOW-706773 adding back extras tests

- src/snowflake/connector/auth/webbrowser.py
- test/unit/test_auth_webbrowser.py
A workaround for when browser doesn't open in webbrowser authentication, e.g.  #SNOW-673771
> SNOW-673771 Print SSO URL before attempting to open window

- setup.py
Fixes #1397 
Local builds on MacOS are failing because the PyArrow upgrade we merged last week requires MacOS SDK to have version > 10.13.  However, `build`/`pip` is building the wheel against a [platform](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform) potentially different than the operating system's [platform](https://docs.python.org/3/library/platform.html#platform.platform). I.e. if your Python distribution (via downloaded installer) is built with MacOSX10.9 SDK, `build`/`pip` …
> Specify min MacOS SDK version for build

- ci/build_windows.bat
> SNOW-730503: pip install awscli in windows build script

- DESCRIPTION.md
- src/snowflake/connector/version.py
- tested_requirements/requirements_310.reqs
- tested_requirements/requirements_311.reqs
- tested_requirements/requirements_37.reqs
- tested_requirements/requirements_38.reqs
- tested_requirements/requirements_39.reqs
Fixes #NNNN
Just adding changelogs
> 3.0.0 release

- DESCRIPTION.md
- src/snowflake/connector/cache.py
- src/snowflake/connector/version.py
- test/unit/test_cache.py
Fixes SNOW-705498
1. white list of attributes to pickle
2. wrap serialization/deserialization to catch all erros
3. move self._get_item_nonlocking out of __init__ definition to a separate method to avoid being collected
> SNOW-705498: Improve the robustness of ocsp response caching to handle error in cases of serialization and deserialization

- src/snowflake/connector/test_util.py
> SNOW-743465: fix snowcli test failure by reverting test util change

- src/snowflake/connector/cursor.py
- src/snowflake/connector/errors.py
- test/integ/test_errors.py
- test/unit/test_errors.py
Fixes #SNOW-701257
Adding query in `ProgrammingError` so that query information is not lost if logging is unset. Related PR https://github.com/snowflakedb/snowpark-python/pull/674
> SNOW-701257: add query attribute to Error class

- DESCRIPTION.md
- src/snowflake/connector/auth/__init__.py
- src/snowflake/connector/auth/idtoken.py
- src/snowflake/connector/connection.py
- test/unit/test_auth_webbrowser.py
Fixes SNOW-733835
We made a bug when we introduced custom auth to the connector. When an ID token expires in storage (i.e. keychain in MacOS) then when we fail to connect we remove the expired token from storage and then propagate the Exception instead of initiating a new externalbrowser auth. In this PR I fix this bug
> SNOW-733835 fix AuthByIdToken expired token auth

- DESCRIPTION.md
- setup.cfg
- src/snowflake/connector/options.py
- test/integ/pandas/test_unit_options.py
Fixes #1447
The logic to detect incompatible versions of PyArrow now uses the standard library (on Python >3.7) and the fundamental library `packaging`.
> Replace runtime dependency on setuptools with modern libraries

- ci/test_windows.bat
Relates to the new 3.0.1 release. SNOW-751214 is used to track this
`tox-external-wheels` uses the internals of `tox` which have changed in version 4 and above. We need to fully switch away from it before we can use the newest versions everywhere.
See that this PR fixes tests:
37: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector37-Win/545/
38: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector38-Win/436/ 
39: https://jenkins.int.snowflakecomputing.com/job/RT-PyConnector39-Win/370/
310: …
> SNOW-751214 pin tox<4 temporarily

- src/snowflake/connector/network.py
- test/unit/test_retry_network.py
test pr for https://github.com/snowflakedb/snowflake-connector-python/pull/1455
The JWT tokens are valid for 1 minute, but still can be enough to steal the tokens from logs (if a hacker has access to the log stream or the log service) and use the token to access the data, potentially to change the user's credentials — if done in an automated way.
Fixes #1454 
Fixes a bug where JWT tokens got leaked into logs in case of post-auth errors.
> Mask JWT tokens in logs in case of post-auth errors

- src/snowflake/connector/cursor.py
SNOW-752200
Fixes #1464
There's no testing for this, `mypy` isn't covering `cursor.py` yet. However; the old type-hints were manually written by me and I suspect it was overwritten by an automated tool in https://github.com/snowflakedb/snowflake-connector-python/commit/eee76d15c6d957f1683440f2152eeabd518ce814.
> SNOW-752200 reverting incorrect type-hint changes

- .github/workflows/stale_issue_bot.yml
Fixes SNOW-756460
This job can help us clean up old issues for reprioritization. Will test with a very large staleDays input first.
> SNOW-756460 Add close stale issue action

- src/snowflake/connector/util_text.py
- test/unit/test_split_statement.py
Description
Before the fix, the remove_comments operation will swallow the final line break, which breaks user query if there is no spaces between two lines.
Testing
Added a new unit test
Fixes SNOW-733718
> SNOW-733718 Fix remove_comments when comments are at end of line

- DESCRIPTION.md
- src/snowflake/connector/cpp/Logging/logging.cpp
- src/snowflake/connector/version.py
Fixes SNOW-761669
we have encountered the same memleak issue before: https://github.com/snowflakedb/snowflake/pull/8226/files
root cause explained: https://stackoverflow.com/questions/5508904/c-extension-in-python-return-py-buildvalue-memory-leak-problem
> SNOW-761669: fix memory leak in c logging

- DESCRIPTION.md
- src/snowflake/connector/storage_client.py
- test/integ/test_large_put.py
Fixes #SNOW-749141. 
Call get_digest even when the file already exists on a stage. The current code skips calling get_digest so the digest is None.
> SNOW-749141: Fix uploading a file > 200M when the same filename already exists in a stage

- .pre-commit-config.yaml
- DESCRIPTION.md
- setup.py
- src/snowflake/connector/auth/webbrowser.py
- src/snowflake/connector/snow_logging.py
- src/snowflake/connector/url_util.py
- test/unit/test_auth_webbrowser.py
- test/unit/test_url_util.py
Fixes SNOW-761004
Currently Python connector does not ensure the validity of the SSO URL and just opens it in the browser. The connector should ensure that the URL is a valid HTTP / HTTPS URL before passing it to the Browser. This PR also adds support for URL encoding strings. This will be used later for encoding Base64 OCSP requests before sending them to the OCSP Responder.
> SNOW-761004 Added URL Validator and URL escaping of strings

- CONTRIBUTING.md
- DESCRIPTION.md
- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
Fixes SNOW-773047
In pandas_tools.py write_pandas tools silently assumes a RangeIndex with step size 1 as this is the default index Pandas generates for a DataFrame. Yet, the index may contain arbitrary values. For non-integer based indices the chunk_helper utility used to write data in chunks to Snowflake uses the sequence protocol, but should use iloc instead. This PR issues a warning for any index that is not a RangeIndex with step=1, but allows to still ingest the data by dropping the index via a fixed …
> [SNOW-773047] Fix chunk-helper, issue explicit warning for non-standard Pandas index

- DESCRIPTION.md
- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
Fixes #NNNN
[Please write a short description of how your code change solves the related issue.
](https://docs.snowflake.com/en/sql-reference/identifiers-syntax#double-quoted-identifiers) a double quote should be replaced by two double quotes in a snowflake identifier.
> SNOW-779375: Fix an issue when calling write_pandas on a pandas dataframe with a column name containing double quote

- DESCRIPTION.md
- src/snowflake/connector/file_transfer_agent.py
- test/integ/test_put_get.py
Description
Today GET command does not support directory structure, so if there are multiple files of the same name on the stage but different paths, downloading them in a single GET command can fail due to race condition.
We are planning to support directory structure in the near future, but it is still useful to print a warning before supporting it to make it less confusing to our users
Testing
integ test
Fixes SNOW-789627
In description
> SNOW-789627 Print warning message if downloading files with same name

- test/integ/test_put_get_medium.py
Fixes broken regression tests.
ENABLE_PARQUET_FILETYPE param was removed [here](https://github.com/snowflakedb/snowflake/commit/6063bbad6c9721749c4e5d849858456a15b930ab). We need to remove it from our tests to fix them.
> remove enable_parquet_filetype param

- test/integ/test_put_get.py
Fixes #NNNN
GZip compression does not always give the same result on the same input stream which causes the test to break when the input stream is compressed. To fix the test, we are setting `AUTO_COMPRESS = FALSE`
> Set AUTO COMPRESS = False for content match test

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
- test/integ/test_multi_statement.py
Description
Today we are modifying statement_params provided by user if they are also a multistatement. This behavior seems awkward and could break user is they are sharing the same statement_params object between multiple queries
Testing
integ
Fixes SNOW-799180
Today we are modifying statement_params provided by user if they are also a multistatement. This behavior seems awkward and could break user is they are sharing the same statement_params object between multiple queries
> SNOW-799180 Do not modify statement_params from user

- DESCRIPTION.md
- src/snowflake/connector/auth/by_plugin.py
- src/snowflake/connector/network.py
- test/unit/test_retry_network.py
Fixes #1269 
Based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403; when we receive a 403 for login-request, re-authenticating does not make a difference. This change fails instantly when 403 http response is received on a login-request.
> SNOW-670921 fail fast on login request with 403 response

- src/snowflake/connector/query_context_cache.py
- test/unit/test_query_context_cache.py
This PR is a follow-up fix for SNOW-754627.
As stated in the JDBC PR side https://github.com/snowflakedb/snowflake-jdbc/pull/1366
Consider a simple situation :
```
current state:
<id, priority, timestamp, context>
<1, 1, 1, None>
<2,2,2, None>
incoming changes:
merge <1, 2,1, None> 
call remove QCE(<1,1,1, None>) -> remove priorityMap(1, <1,1,1, None>)
call add QCE(<1,2,1, None>) -> add priorityMap(2, <1,2,1, None>) this map insertion will fail due to collision of priority key(there are two priority keys of …
```
> SNOW-754627 fix priority switch corner case error

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
Fixes #1423
type ResultMetaData fields as optional where they can be `None`
> fix: type ResultMetaData fields as optional

- .github/dependabot.yml
Description
Until we get green light from security, we will stop dependent bot.
Testing
N/A
Fixes SNOW-811030
> SNOW-811030 Disable dependent bot from github actions

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- src/snowflake/connector/converter.py
- test/integ/test_bindings.py
Fixes SNOW-770678
with the integer representation, the date can only be represented at maximal `31536000000 ` seconds which is `May 3, 2969 12:00:00 AM`. Any date beyond the date will be taken as milliseconds/nanoseconds. leading to incorrect date.
In the PR, we use the simple string form the represent the date
> SNOW-770678: Fix incorrect date conversion in bulk insertion

- src/snowflake/connector/cursor.py
Fixes #1570
Moves a `TODO` comment out of a docstring in `cursor.py` so Sphinx with sphinx-immaterial theme doesn't explode when building API reference docs.
> ENGDOC-204 fix Sphinx-busting docstring

- ci/test_docker.sh
Fixes SNOW-826296
Fixing Jenkins Arm tests.
> SNOW-826296 missing parameter in script

- ci/test_darwin.sh
Fixes SNOW-826794
Fixing Mac Jenkins tests now that they're working again. Example successful run: https://ci-dev-122.int.snowflakecomputing.com/job/RT-PyConnector38-Mac/9/console
> SNOW-826794 fix mac tests

- src/snowflake/connector/sf_dirs.py
Fixes SNOW-834415
We use the `ensure_exists` convenience feature of `platformdirs` this unfortunately creates our config folder at import time. Which will not work in Lambda. In this PR I remove this flag.
Successful run: https://ci-dev-122.int.snowflakecomputing.com/job/RT-PyConnector37-PC-Lambda/186/console
> SNOW-834415 Dont auto create config folder

- src/snowflake/connector/config_manager.py
Complements SNOW-802807 
It was brought to my attention that I forgot to add this one reference to `config_manager.py`'s `__all__`. Correcting my mistake here.
> SNOW-802807 adding missing reference to config_manager.py __all__

- DESCRIPTION.md
- setup.cfg
- src/snowflake/connector/sf_dirs.py
Fixes #NNNN
New `platformdirs` [release](https://pypi.org/project/platformdirs/3.6.0/) has added a new property to the abstract class that we implement. Effectively blocking us to instantiate one of these classes. This has broken our unit tests everywhere. In this PR I lock down our pinning more to prevent this in the future and I update our implementation too.
> fixing platformdirs incompatibility

- DESCRIPTION.md
- src/snowflake/connector/sf_dirs.py
- test/unit/test_configmanager.py
Relates to SNOW-802807
We discovered a bug where `appname` and possibly `version` was being appended to `SNOWFLAKE_HOME`.
What this lead to is that configuration file location would become `/Users/mkeller/.snowflake/snowflake/config.toml` when `~/.snowflake` existed.
In this PR I remove appending these pieces to the path and update the accompanying unit tests. I guess I knew this when I wrote this code, but it never occurred to me that this was not what we wanted
> SNOW-802807 SNOWFLAKE_HOME config file resolution bug

- tox.ini
> SNOW-851522: pin pre-commit to use py38 as isort in precommit doesn't support py37 anymore

- src/snowflake/connector/cache.py
- src/snowflake/connector/ocsp_snowflake.py
- test/unit/test_cache.py
follow upon the first PR of SNOW-833713, revert the part that introduces `try_saving_when_setting` in the commit: https://github.com/snowflakedb/snowflake-connector-python/commit/398d1ea770ebd506edef7218943f3a971b19f48f
revert unnecessary change
> SNOW-833713: revert try setting item when saving parameter

- DESCRIPTION.md
- src/snowflake/connector/network.py
- test/unit/test_retry_network.py
Fixes SNOW-847497
if the https connection is reset by server, we abandon the old one and let urllib3 create new connection
> SNOW-847497: recreate session connection if reset by server

- src/snowflake/connector/_query_context_cache.py
- src/snowflake/connector/connection.py
- test/unit/test_query_context_cache.py
Fixes #SNOW-862821
When I was helping ODBC team to debug their query context related issue. I found that both ODBC and python connector have an inconsistent query context JSON serialization behavior for HTTP response. To be precise:
1. The json field name should be `queryContextDTO` instead of `queryContext` to keep consistent with JDBC/GS.
2. The entire `queryContextDTO` field is also not a string, it should be an object (dict in python).
3. The `context` subfield is not a string, but an `OpaqueContextDTO` …
> SNOW-862821 [Python Connector] Update query context cache response body to align with JDBC

- DESCRIPTION.md
- src/snowflake/connector/result_set.py
- test/integ/pandas/test_arrow_pandas.py
SNOW-870322 Allow pass type_mapper to arrow to_pandas()
This PR allows fetch_pandas_batches() and fetch_pandas_all() to bypass kwargs to arrow.to_pandas(), e.g., we can pass type_mapper to it.
> SNOW-870322 Allow pass type_mapper to arrow to_pandas()

- DESCRIPTION.md
- src/snowflake/connector/cache.py
- src/snowflake/connector/constants.py
- src/snowflake/connector/ocsp_snowflake.py
- test/unit/test_cache.py
- tox.ini
Fixes #1627 
In this PR I hopefully fix the underlying issue causing `pickle.dump` segfaults.
The just of what I found is that calls calling `_save` did not hold `self._lock` which could lead to other threads modifying the data in the cache while dumping was going on and more issues were found later. I verified this with `assert` statements.
I also updated all the unsafe call places that I could find. I left in the assert statements for now to catch other unsafe calls.
I included a draw.io graph for how the …
> SNOW-856569 making save actions thread-safe

- DESCRIPTION.md
- src/snowflake/connector/auth/okta.py
- src/snowflake/connector/errors.py
- src/snowflake/connector/network.py
- test/unit/test_auth_okta.py
Fixes SNOW-862388
refresh token if okta authentication gets throttled because okta token is one time token, it gets invalid once it's used, so we need a new one 
> SNOW-862388: improve okta authentication retry logic

- DESCRIPTION.md
- src/snowflake/connector/config_manager.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/constants.py
- src/snowflake/connector/errors.py
- test/integ/test_connection.py
- test/unit/test_configmanager.py
Fixes SNOW-873456
In this PR I add a last second change to new configuration file feature. It allows us to optionally slice configuration files into multiple files. As an example consider:
```toml
[connections.snowflake]
account = "snowflake"
user = "snowball"
password = "password"
[settings]
output_format = "json"
```
Is equivalent to:
```toml
[settings]
output_format = "json"
```
```toml
[snowflake]
account = "snowflake"
user = "snowball"
password = "password"
```
> SNOW-873456 config file slicing

- DESCRIPTION.md
- src/snowflake/connector/auth/keypair.py
- src/snowflake/connector/connection.py
- test/integ/test_key_pair_authentication.py
- test/unit/test_auth_keypair.py
This can be used to externalize the JWT encoding process (see linked issue for motivation and details).
For further motivation, see https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/ – managed keys (software- or hardware protected) are the answer to this problem.
Fixes #1276.
This change makes use of the fact that `RSAPrivateKey` is already an interface (ABC) and the [JWT library](https://pypi.org/project/jwt/) is fully compatible with a custom implementation, for example one that externalizes the signing process to a cloud-based service such as Azure Key Vault.
Note …
> Add support for specifying 'RSAPublicKey' instance instead of raw bytes

- DESCRIPTION.md
- src/snowflake/connector/auth/okta.py
- test/unit/test_auth_okta.py
Fixes SNOW-862388
there's a bug in the implementation that the new generated token got appended to the url already with old token
so making the new token not working at all
> SNOW-862388: fix okta retry bug

- DESCRIPTION.md
- src/snowflake/connector/network.py
- test/unit/test_proxies.py
This fixes an error that would arise when using a SOCKS5 proxy.
Fixes #1550
This code skips setting the `proxy_headers` property of the ProxyManager if we are using a SOCKS5 proxy.
For more details, see the [related issue](https://github.com/snowflakedb/snowflake-connector-python/issues/1550).
> Fix 'SOCKSProxyManager' object has no attribute 'proxy_headers' error

- src/snowflake/connector/ocsp_snowflake.py
- test/unit/test_ocsp.py
Description
When there is connection error, we will get None as OCSP response, which should not be written to cache.
Testing
unit test
Fixes SNOW-890625
> SNOW-890625 Do not write cache when we have no OCSP response

- DESCRIPTION.md
- src/snowflake/connector/telemetry_oob.py
- test/unit/test_telemetry_oob.py
Fixes SNOW-897148: telemetry log event tags dictionary keys only accept int/str, not accepting the class `TelemetryField`
> SNOW-897148: fix oob telemetry tags generation

- DESCRIPTION.md
- src/snowflake/connector/vendored/urllib3/response.py
This is equivalent to cherry-picking [`fd2759aa16b12b33298900c77d29b3813c6582de`](https://github.com/urllib3/urllib3/commit/fd2759aa16b12b33298900c77d29b3813c6582de) onto the current vendored version `1.26.15`. We are merging the cherry pick to unblock release.
Fixes #1425
urllib3 does not do content-length checking.
result_batch.py does a get request in line 298, which can therefore in case of connection issues return an incomplete response. This is passed directly to an ArrowIterator. The already existing retry mechanism does not catch this as no Exception is generated.
Please …
> SNOW-739316 Enforce content-length checking in vendored urllib3

- DESCRIPTION.md
- src/snowflake/connector/config_manager.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/errors.py
- test/unit/test_configmanager.py
Fixes SNOW-878611
In this PR I modify doc-strings and rename all parser occurrences to manager while being backwards compatible.
> SNOW-878611 renaming and aliasing CONFIG_PARSER to CONFIG_MANAGER

- DESCRIPTION.md
- src/snowflake/connector/config_manager.py
- test/unit/test_configmanager.py
Fixes SNOW-902097 and SNOW-902098
In this PR I add the capability to add default values to ConfigOption class and am adding the first ConfigOption that is going to use it `default_connection_name` that defaults to `default`.
> SNOW-902097 adding default_connection_name and default value to ConfigOption

- src/snowflake/connector/__init__.py
- src/snowflake/connector/config_manager.py
- src/snowflake/connector/connection.py
- test/integ/test_connection.py
- test/unit/test_connection.py
Fixes SNOW-891470
Now that we have flushed out how the configuration file option `default_connection_name` should work I add actual support for it.
> SNOW-891470 adding implementation for default_connection_name

- DESCRIPTION.md
- src/snowflake/connector/telemetry_oob.py
- test/unit/test_telemetry_oob.py
Fixes [SNOW-895151: Non Thread Safe Singleton Telemetry Service in Python](https://github.com/snowflakedb/snowflake-connector-python/issues/1700)
Adding a lock guarding the instantiation of `TelemetryService` prevents multiple threads from entering `__init__` and violating the singleton constraint.
> Implement thread safety during instantiation of TelemetryService

- DESCRIPTION.md
- src/snowflake/connector/ocsp_snowflake.py
- test/unit/test_ocsp.py
Fixes #SNOW-872568
Porting fix for getting the correct retry link for oscp private link url
> SNOW-872568: Fix retry oscp URL for private link

- DESCRIPTION.md
- src/snowflake/connector/vendored/urllib3/__init__.py
- src/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py
Fixes #1713
Patching out https://github.com/snowflakedb/vendored-urllib3/commit/f95b9640604e7dd70d50d81f68fd14a36c082841
> SNOW-899912 patching out urllib3.contrib.pyopenssl deprecation warnings

- DESCRIPTION.md
- ci/test_fips_docker.sh
- setup.cfg
- src/snowflake/connector/connection.py
- src/snowflake/connector/encryption_util.py
- src/snowflake/connector/file_util.py
- src/snowflake/connector/ocsp_asn1crypto.py
- test/integ/test_connection.py
This reverts commit 6398696a03f3a13b0ee0f2d140988f2b146423eb.
snowsql depends on the two other cryptography libs
removing the dependency breaks snowsql
this is a BCR change
Fixes #NNNN
> Revert "SNOW-843716: cryptography dep cleanup (#1773)"

- test/unit/test_telemetry_oob.py
SNOW-943025, Fixes flaky OOB test
since pytests can run test in parallel and TelemetryService is a singleton, other tests might encounter error logged into the queue of the OOB Telemetry simultaneously leading to assert telemetry.size() == 0 failure, here we check that the OCSP exception event in the test is flushed
> SNOW-943025: improve flaky OOB test

- .gitignore
- DESCRIPTION.md
- setup.py
- src/snowflake/connector/constants.py
- src/snowflake/connector/converter.py
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/FixedSizeListConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/FixedSizeListConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.hpp
- test/integ/pandas/test_arrow_pandas.py
- test/integ/test_arrow_result.py
- test/integ/test_cursor.py
Fixes SNOW-950840
Add support for vectors (soon in Private Preview) to the connector. This primarily consists of Arrow deserialization logic.
I will follow these changes up with parsing logic for the new result metadata fields so that the vector field type definition in `constants.py` can use the correct pyarrow type. Right now, we return `pa.binary()` for `FieldType.pa_type` since we don't have access to the vector's type and dimension (which are needed by `pa.list_`). This bypass is functionally equivalent …
> SNOW-950840 Add support for the vector data type

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- src/snowflake/connector/converter.py
- test/integ/test_bindings.py
Fixes SNOW-966444
the previous fix is incomplete, when TEXT type, date format is not allowed to set.
we switch back to the old milliseconds approach, and handle case according to the spec
> SNOW-966444: Fix date binding with qmark

- ci/test_darwin.sh
- test/unit/test_ocsp.py
Fixes SNOW-901801
in our regression test env, we only have one mac node, and tests of different python versions are paralleled, so race condition takes place when tests are reading/writing the same ocsp cache file on disk leading to flaky behavior.
to fix the issue, in the test we mock patch the module variable cache to use a different file
also we fix the shell script which misses the coverage part
> SNOW-901801: fix flaky test of ocsp cache in regression test

- src/snowflake/connector/backoff_policies.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/file_transfer_agent_async.py
- src/snowflake/connector/network_async.py
- src/snowflake/connector/ocsp_asn1crypto.py
- src/snowflake/connector/ocsp_asn1crypto_async.py
- src/snowflake/connector/ocsp_snowflake.py
- src/snowflake/connector/ocsp_snowflake_async.py
- src/snowflake/connector/result_batch.py
- src/snowflake/connector/s3_storage_client_async.py
- src/snowflake/connector/ssl_connector.py
- src/snowflake/connector/ssl_wrap_socket.py
- src/snowflake/connector/storage_client_async.py
- test/unit_async/test_session_manager.py
[See the related epic issue here](https://snowflakecomputing.atlassian.net/browse/SNOW-912527).
[See the project doc here (not fully up to date)](https://docs.google.com/document/d/1gGuDv_6p5GsiJw9IaBFdvLpRJHN6-0MxsYzLW8mDQco/edit?usp=sharing).
The relevant issues are:
- [Subclass aiohttp.TCPConnector to inject OCSP verification](https://snowflakecomputing.atlassian.net/browse/SNOW-973746)
Most changes are explained in comments prefixed with `# YICHUAN: ...`. This pull request is for review purposes only. A formal pull request will be made when merging into main.
> SNOW-912527 Milestone 2: Inject OCSP verification into aiohttp

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
- src/snowflake/connector/result_set.py
- test/integ/pandas/test_arrow_pandas.py
Fixes SNOW-966003, dup PR: https://github.com/snowflakedb/snowflake-connector-python/pull/1801#issuecomment-1861345001
> SNOW-966003: Fix Arrow return value for zero-row queries

- DESCRIPTION.md
- test/README.md
- test/integ/test_autocommit.py
- test/integ/test_converter_null.py
- test/integ/test_cursor.py
- test/integ/test_transaction.py
- test/unit/test_configmanager.py
- test/unit/test_encryption_util.py
- tox.ini
Fixes #NNNN
* In several cases, we need to dig the `warehouse` parameter out of the connection dictionary, and use that explicitly rather than rely on an implicit user default warehouse.
* Add `setuptools` as an explicit tox provisioning requirement.
* Don't assume that unsetting the `SNOWFLAKE_HOME` environment variable is enough to pass the fallback test, since the local user may have `~/.snowflake`, and if they do, this is used as the implicit fallback.  Use a fake home in a temporary directory instead, …
> SNOW-999576: Fix several local test problems

- DESCRIPTION.md
- setup.py
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/ArrayConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/ArrayConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowTableIterator.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/MapConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/MapConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/ObjectConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/ObjectConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.hpp
- test/integ/test_arrow_result.py
Implements SNOW-1000283
This change adds support for structured types. Specifically types defined on Snowflake with these definition types:
```
OBJECT(field_1, value_type_1, ...)
ARRAY(element_type)
MAP(key_type, value_type)
```
These types are currently returned as json encoded strings and will continue to be unless the `ENABLE_STRUCTURED_TYPES_IN_CLIENT_RESPONSE` session parameter is true.
Review Notes:
MAP previously was not a supported type in the connector, but was on the DB side. This change adds the …
> SNOW-1000283: Add support for Structured Types.

- DESCRIPTION.md
- setup.cfg
Fixes SNOW-1049425
keyring < 23.1.0 has a [security loophole](https://github.com/jaraco/keyring/issues/274) where malicious user could place ddl at a harcoded path that non-admin users could write to on Windows. The problematic code is removed in 23.1.0. Hence we could address this vulnerability by capping the dependency on `keyring` to >= 23.1.0.
> SNOW-1049425 Bump keyring dependency lower bound to address security vulnerability

- DESCRIPTION.md
- src/snowflake/connector/auth/webbrowser.py
- test/unit/test_auth_webbrowser.py
Note: Copy&Pasting the original message from @podung , in his original PR [here](https://github.com/snowflakedb/snowflake-connector-python/pull/1686)
Fixes #1251 
* Improved `externalbrowser` auth in containerized environments
* Instruct browser to not fetch `/favicon `on success page (can cause failure to parse subsequent tokens)
* Simple retry strategy on empty socket.recv (occurs frequently when containerized)
* Add `SF_AUTH_SOCKET_REUSEPORT` flag (usage: `SF_AUTH_SOCKET_REUSEPORT=true`) to set the …
> Robust containerized externalbrowser rebased

- src/snowflake/connector/cursor.py
Fixes part of #1000284
This PR removes the ResultMetadataV2Field class. This class is functionally the same as the ResultMetadataV2 class with the one difference being it can be created without a name. With structured types incoming the metadata can be arbitrarily nested so I don't think it makes sense to have separate classes for the top level metadata and the child metadatas. 
The only place this class is referenced is the ResultMetadataV2.from_column and I've replaced that with an equivalent initializer …
> SNOW-1000284: Refactor MetadataV2 ahead of structured types.

- src/snowflake/connector/connection.py
- test/unit/test_connection.py
Fixes #1877
The code checks to see if the private_key_file_pwd parameter is a string, if so it converts it to bytes using with utf-8 encoding prior to loading the PEM file.
> Fix for an issue where specifying a private_key_file_pwd in a connections.toml file causes an error.

- src/snowflake/connector/local_storage_client.py
- test/unit/test_local_storage_client.py
Description
When running `GET` queries in a local deployment, if a prefix path is provided in the `GET` query, the connector doesn't correctly generate the source file location. See SNOW-1208964 for a detailed example.
Testing
Fixes SNOW-1208964
When creating a destination filepath for `PUT`, the connector uses only the basename of the file. This works even with subdirectories because in the `PUT` case, `stage_info["location"]` contains the subdirectory path. 
For `GET`, the connector is using the same logic …
> SNOW-1208964: Fix source file path resolution for local storage client

- DESCRIPTION.md
- src/snowflake/connector/pandas_tools.py
- test/integ/pandas/test_pandas_tools.py
Addresses [SNOW-1184290](https://snowflakecomputing.atlassian.net/browse/SNOW-1184290)
Builds on the changes committed in SNOW-733213 to enforce truncate-only behavior by excluding CREATE TABLE IF NOT EXISTS when auto_create_table = False and overwrite = True.
[SNOW-1184290]: https://snowflakecomputing.atlassian.net/browse/SNOW-1184290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  Fix write_pandas() truncate-only flow to prevent CREATE TABLE IF NOT EXISTS

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- test/integ/test_connection.py
the `__del__` method is unstable and gets called at random timing.
in one of the recent report, we found the `__del__` is causing circular import issue.
as a short term fix, we fix by moving away from `__del__` method to using `atexit` to clean up connection at intepreter shutdown time.
long term fix plan here: SNOW-1218851
> SNOW-996732: improve clean up logic of connection

- DESCRIPTION.md
- src/snowflake/connector/constants.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/options.py
- test/integ/pandas/test_arrow_pandas.py
Implements: #1000284
This change adds support for structured types to ResultMetadataV2 which should allow for accurate schemas to be created in the snowpark python repo. Notable changes:
- Changed the from_column handler to support other structured types as well as nested structured types. 
- Added MAP as a supported metadata type.
- Added relevant default initializers for pyarrow in order to support casting result batches to pyarrow tables.
- Added a test that tests that the default initializers for pyarrow …
> SNOW-1000284: Add support for structured types to ResultMetadataV2

- setup.cfg
- src/snowflake/connector/result_batch.py
- test/integ/test_arrow_result.py
Fixes #NNNN
This PR removes the maps_as_pydicts parameter that would cause a dependency on pyarrow 13.0.0. This means that maps returned in pandas tables will instead be returned as lists of tuples instead. Users are still free to pass in the maps_as_pydicts parameter to fetch_all_pandas in order to get dictionary objects back instead.
> SNOW-0000000: Revert pyarrow 13.0.0 dependency.

- DESCRIPTION.md
- src/snowflake/connector/version.py
- tested_requirements/requirements_310.reqs
- tested_requirements/requirements_311.reqs
- tested_requirements/requirements_312.reqs
- tested_requirements/requirements_38.reqs
- tested_requirements/requirements_39.reqs
Fixes #NNNN
This release should be fairly light. There are two main things we're pushing as part of it:
1. Added support for structured types to fetch_pandas_all.
As part of the structured types initiative this PR adds support for fetching structured data as pandas dataframes. This is a new functionality and shouldn't have any effect on current queries.
2. Fixed an issue that endpoint for China s3 is not formed correctly.
@sfc-gh-yuwang can …
> MINOR: Bumped up PythonConnector MINOR version from 3.9.1 to 3.10.0

- DESCRIPTION.md
- src/snowflake/connector/ocsp_asn1crypto.py
- test/unit/test_ocsp.py
Fixes #NNNN
SHA3-384 is a different algorithm from SHA384, and it's not supported by the asn1crypto library.
this PR fixes the sha algorithm mapping info
> SNOW-1412405: fix ocsp validating sha384 signed certificate

- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
Allows us to pass `dataframe_ast` to `cmd_query`. This will be used by Snowpark to communicate AST-level requests.
To use this in your own development, clone this Git repo and follow instructions in `/CONTRIBUTING.md`.
> [feature branch] Initial checkin for Phase 0 changes to the connector

- DESCRIPTION.md
- src/snowflake/connector/config_manager.py
- test/unit/test_configmanager.py
Fixes #1959
`path.exists` will raise a PermissionError if there is no permission on the parent directory of config file path
> SNOW-1460707: Fix permission error when there is no permission on the parent directory of config file path 

- ci/docker/connector_test_fips/Dockerfile
Fixes SNOW-1518775
centos7 reaches end of life and https://mirrorlist.centos.org/ is gone. leading to docker image could not be built.
solution provided by
https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
> SNOW-1518775: fix connector fips docker image

- src/snowflake/connector/network.py
> SNOW-1514764: Support Tracing in SPCS runtime

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- test/integ/test_connection.py
* SNOW-1511108
* https://github.com/snowflakedb/snowflake-sqlalchemy/issues/509
When coming from (snowflake-)sqlalchemy's Engine, the `client_session_keep_alive_heartbeat_frequency` option seems to come as string, which then will crash the connector with
```
..
File "/usr/local/lib/python3.11/site-packages/snowflake/connector/connection.py", line 1680, in _validate_client_session_keep_alive_heartbeat_frequency
elif self.client_session_keep_alive_heartbeat_frequency > real_max:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
```
2. Fill …
> SNOW-1511108 SQLAlchemy heartbeat frequency parsed as string

- src/snowflake/connector/connection.py
Fixes #NNNN
It can help internal teams to understand the meaning of this parameter when potentially overwriting this property for a new client type. 
> SNOW-1473577: Add comment for `internal_application_name` in connection parameters

- DESCRIPTION.md
- src/snowflake/connector/constants.py
- src/snowflake/connector/storage_client.py
Fixes [SNOW-1468259](https://snowflakecomputing.atlassian.net/browse/SNOW-1468259)
By default, `request` do not time out unless a timeout value is set explicitly. A user recently reported that their file transfer would sometimes hang indefinitely at reading from a request call. This PR aims to mitigate this issue by specifying a default connection timeout of 10 seconds and socket read timeout of 10 minutes. Please see 
https://requests.readthedocs.io/en/latest/user/advanced/#timeouts
[SNOW-1468259]: …
> SNOW-1468259 Add connection timeout and read timeout to storage client request

- test/integ/test_arrow_result.py
Fixes #1539600
This PR adds a wrapper to the connection object in structured type tests that enables required parameters when running in an env that allows structured types. This allows the tests to run when the parameters have not been set at the account level.
N/A
> SNOW-1539600: Refactor structured type tests to explicitly set params

- DESCRIPTION.md
- src/snowflake/connector/connection.py
Fixes SNOW-1526475
currently private_key of string type is not supported, fixing the type hint
we will add string support in another PR
> SNOW-1526475: fix type hint for private_key

- test/integ/test_put_get_with_gcp_account.py
> Fix gcp test so that gcs downscoped is always enabled

- DESCRIPTION.md
- src/snowflake/connector/sf_dirs.py
- test/unit/test_configmanager.py
Fixes [#2018](https://github.com/snowflakedb/snowflake-connector-python/issues/2018)
Use `pathlib` instead of `os` to resolve default config file paths 
> Refactor default config location resolution to use pathlib instead of os

- DESCRIPTION.md
- setup.cfg
It's for https://github.com/snowflakedb/snowflake-connector-python/issues/2015
`snowflake-export-certs` script is still referenced in `setup.cfg`, despite its backing module was removed ~6 years ago already in https://github.com/snowflakedb/snowflake-connector-python/pull/138 (commit https://github.com/snowflakedb/snowflake-connector-python/commit/061f20d6da0f8a294e6b77e106e1ecedd456985f, released with PythonConnector 1.7.2). This PR removes the reference to the script.
> SNOW-1613751 remove reference to script `snowflake-export-certs`

- DESCRIPTION.md
- src/snowflake/connector/network.py
- test/integ/test_network.py
Fixes SNOW-1562604
add retry when polling query result and the response is None.
this happens when there is a 499 error happening between client and server.
without the fix, the client stopped retrying and errored out.
with the fix, we will keep retrying
> SNOW-1562604: enhance error handling when polling query result

- DESCRIPTION.md
- src/snowflake/connector/util_text.py
- test/unit/test_construct_hostname.py
> Infer TLD for China based on region in account

- DESCRIPTION.md
- src/snowflake/connector/ocsp_snowflake.py
Relevant to https://github.com/snowflakedb/snowflake-connector-python/issues/2044
Default behaviour for OCSP is Fail-Open when we cannot do a proper OCSP check; the driver continues to connect to Snowflake while logging a message which is intended to be warning (since the connection still happens). The verbiage of the warning text is clearly reflecting the intention of it being warning - however, we log this warning line at `ERROR` loglevel instead of `WARNING`, which apparently causes unnecessary log cluttering in certain scenarios. 
This small PR aims to change the loglevel for the …
> SNOW-1650640 changed OCSP fail-open warning message loglevel to warning (from error)

- .github/workflows/build_test.yml
Fixes #NNNN
our test cov has not been updated for a while: https://app.codecov.io/github/snowflakedb/snowflake-connector-python
because v3 upload action hits rate limit error
updating to v4 resolves the issue
> bump github action version to fix coverage report

- src/snowflake/connector/cursor.py
Fixes #2009
Update documentation to show the differences between `query_result` and `get_results_from_sfqid` APIs.
> SNOW-1559272: Document differences b/w query result APIs

- src/snowflake/connector/aio/_result_batch.py
- test/integ/aio/test_cursor_async.py
> SNOW-1654538: asyncio download timeout setting

- src/snowflake/connector/aio/_azure_storage_client.py
- src/snowflake/connector/aio/_file_transfer_agent.py
- src/snowflake/connector/aio/_gcs_storage_client.py
- src/snowflake/connector/aio/_s3_storage_client.py
- src/snowflake/connector/aio/_storage_client.py
- test/integ/aio/test_put_get.py
- test/integ/aio/test_put_get_medium.py
- test/integ/aio/test_put_get_with_aws_token_async.py
- test/integ/aio/test_put_get_with_azure_token_async.py
- test/integ/aio/test_put_get_with_gcp_account_async.py
- test/integ/test_put_get_with_gcp_account.py
- test/unit/aio/test_gcs_client_async.py
- test/unit/aio/test_put_get_async.py
> SNOW-1728340: support gcp and azure

- test/unit/test_backoff_policies.py
> SNOW-1540289: add test for max policy backoff time

- src/snowflake/connector/aio/_file_transfer_agent.py
- src/snowflake/connector/aio/_s3_storage_client.py
- test/integ/aio/test_put_get_with_aws_token_async.py
- test/unit/aio/test_s3_util_async.py
> SNOW-1628850: fix s3 accelerate logic

- src/snowflake/connector/auth/_auth.py
- src/snowflake/connector/secret_detector.py
- test/unit/test_log_secret_detector.py
Fixes SNOW-1657037 SNOW-1642759
This change removes a log line that would leak secrets as well as changes another from a blacklist approach to a whitelist approach.
Stored proc does not share the auth submodule.
> SNOW-1657037: Remove secrets from debug logs.

- src/snowflake/connector/azure_storage_client.py
- test/integ/test_put_get_with_azure_token.py
Fixes SNOW-1650124
This PR passes params through to the requests library so that Azure tokens can be passed to requests via params. This allows logging to avoid printing the secret information.
Azure storage client does not exist in stored proc connector.
> SNOW-1650124: Pass Azure SAS Token via params

- src/snowflake/connector/aio/_network.py
> SNOW-1708720: Error is raised at debug level when not closing connection

- DESCRIPTION.md
- src/snowflake/connector/network.py
- test/unit/test_connection.py
Fixes #2084 
In this PR I fix an error where sometime injecting OpenTelemetry headers into our own causes Exceptions to be thrown.
> SNOW-1763555 update how HTTP headers are requested from OpenTelemetry

- DESCRIPTION.md
- setup.cfg
Fixes SNOW-1836910
In this PR I raise the minimum pyopenssl version we require.
> SNOW-1836910 bump pyopenssl

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/file_transfer_agent.py
- test/integ/test_put_get.py
- test/unit/test_put_get.py
Fixes SNOW-1817982
In this PR I introduce a new connection level parameter that can limit the IO-bound ThreadPoolExecutors' sizes.
> SNOW-1817982 iobound tpe limiting

- DESCRIPTION.md
- README.md
Fixes #NNNN
add instruction for package signature verification
> SNOW-1862674: update readme for signature verification

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
SNOW-1868288
Apparently for some workflows (https://github.com/snowflakedb/snowflake-connector-python/issues/2126), the INFO level of current logging is excessive. Aiming to set it to DEBUG - if needed for troubleshooting, one usually uses verbose loglevels anyways.
> SNOW-1868288 log level to debug in chunk rowcount logging

- DESCRIPTION.md
- src/snowflake/connector/auth/keypair.py
- src/snowflake/connector/connection.py
- test/integ/test_key_pair_authentication.py
- test/unit/test_auth_keypair.py
Fixes #2133
Support base64-encoded DER private keys. We currently support raw DER `bytes`, and now we will also support base64-encoded DER strings. This functionality is useful for passing private keys through environment variables and other configuration mechanisms.
> Support base64-encoded DER private keys

- src/snowflake/connector/cursor.py
SNOW-1882588 Allow Empty Sql Text when Dataframe Ast is Presented
> SNOW-1882588 Allow Empty Sql Text when Dataframe Ast is Presented

- test/unit/test_cursor.py
SNOW-1882588 Add Test for PR https://github.com/snowflakedb/snowflake-connector-python/pull/2136
> SNOW-1882588 Add Test for PR 2136

- .github/workflows/build_test.yml
Fixes #NNNN
QEMU assisted Linux Arm64 wheel compilation is having a hard time since Friday. In this PR I pin it back to an old version which seems to be working. Please see https://github.com/tonistiigi/binfmt/issues/215 for more information!
> pin qemu used for arm64 linux wheels 

- DESCRIPTION.md
- src/snowflake/connector/_utils.py
- src/snowflake/connector/pandas_tools.py
- src/snowflake/connector/version.py
- test/integ/pandas/test_pandas_tools.py
- tested_requirements/requirements_310.reqs
- tested_requirements/requirements_311.reqs
- tested_requirements/requirements_312.reqs
- tested_requirements/requirements_39.reqs
> Changed not to use scoped temp stage

- DESCRIPTION.md
- setup.cfg
Fixes SNOW-1891253
From the linked issue https://github.com/snowflakedb/snowflake-connector-python/issues/2140 it looks like we're now incompatible with other tools, which require pyopenssl 25.0.0. Checking the CHANGELOG over there, there's no claim for backward-incompatible changes, so bumping the requirement upper boundary. 
> SNOW-1891253 bump pyopenssl upper boundary to <26.0.0 from <25.0.0

- DESCRIPTION.md
- src/snowflake/connector/connection.py
This workarround is only for unsoportted python 2.7
Fixes #NNNN
Delete the old workarround. as documented on https://bugs.python.org/issue7980 is only for python2.7
> delete workarround for pyton2.7

- DESCRIPTION.md
- setup.cfg
Fixes SNOW-1886670
We are seeing a strange bug on Azure Batch where `pyarrow==19.0.0` is causing our nanoarrow implementation to not work. While we are investigating this issue I'm going to introduce a version pin to not allow users to break.
This should be a short-term workaround only and the pin should not sick around for long!
> SNOW-1886670 pin pyarrow

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- test/integ/test_connection.py
SNOW-1920533
Public link OCSP Cache server url is `ocsp.snowflakecomputing.com` but in privatelink environment it works differently, and should look like `ocsp.accountname.region.privatelink.snowflakcomputing.com`. This hostname for OCSP Cache is determined based on the connection configuration (account/host). 
Since earlier we were looking for pattern `.privatelink.snowflakecomputing.` to be present in account/host, if user specified account as `MYACCOUNT.REGION.PRIVATELINK`, it resulted host becoming partly uppercase and thus not matching the above pattern.
Fix aims to lowercase …
> SNOW-1920533 match privatelink in hostname to setup correct privatelink OCSP Cache url even if user specifies account in UPPERCASE

- DESCRIPTION.md
- src/snowflake/connector/azure_storage_client.py
- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/encryption_util.py
- src/snowflake/connector/file_transfer_agent.py
- src/snowflake/connector/file_util.py
- src/snowflake/connector/gcs_storage_client.py
- src/snowflake/connector/local_storage_client.py
- src/snowflake/connector/s3_storage_client.py
- src/snowflake/connector/storage_client.py
- test/integ/test_put_get.py
This PR adds `unsafe_file_write` flag to connection class. The security patch applied in 3.13.1 has narrowed the permissions of files downloaded with GET to 600. This change seems to be inconvenient for some customers that were relying on the previous behaviour in their workflows so after discussion with the support team we decided to add a flag that restores the previous behaviour of saving files downloaded with GET with 644.
The parameter was added to all cloud interfaces, the default value is False which means the strict permissions will be applied.
The test had to be fixed since due to the compression on PUT the permissions weren't verified on the proper file.
> SNOW-1944208 add unsafe write flag

- DESCRIPTION.md
- setup.py
- src/snowflake/connector/arrow_context.py
- src/snowflake/connector/converter.py
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/DecFloatConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/DecFloatConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.hpp
- test/integ/test_decfloat.py
- test/unit/test_converter.py
Implements [SNOW-1915469](https://snowflakecomputing.atlassian.net/browse/SNOW-1915469)
This PR adds basic decimal float (DECFLOAT) data type support to the python connector.
- Supports ARROW and JSON result format. DECFLOATs are converted to Decimal or numpy.float64
- Server-side binding support using explicit Snowflake type specification as Decimal is already mapped to FIXED by default
- No Pandas support
[SNOW-1915469]: …
> SNOW-1915469 Basic support for DECFLOAT type

- test/integ/test_decfloat.py
- test/unit/test_converter.py
Recently merged changes were causing the old driver tests to fail due to missing dependency. This PR skips the decfloat test on the old driver to prevent the failure.
> skip decfloat test in olddriver tests

- ci/docker/connector_test/Dockerfile
- ci/set_base_image.sh
- ci/test_linux.sh
- test/unit/test_wiremock_client.py
- Use fixed version of manylinux image to enable `yum` while keeping the `latest` tag as a backup.
- Add install openjdk 11 step to Dockerfile to enable running wiremock daemon
- Enable wiremock healthcheck test on Jenkins
> SNOW-1927118 Enable wiremock tests on Jenkins

- src/snowflake/connector/auth/_http_server.py
- test/unit/test_auth_callback_server.py
> SNOW-1825495 Improve HTTP server targeted at serving OAuth redirects with timeouts and tests

- src/snowflake/connector/auth/workload_identity.py
This is a tiny bug fix to https://github.com/snowflakedb/snowflake-connector-python/pull/2203 which added support for Workload Identity Federation. Instead of raising an error, this line was accidentally returning it.
> Replace return with raise in error check

- DESCRIPTION.md
- src/snowflake/connector/cursor.py
- test/integ/test_cursor.py
Fixes SNOW-2007887
there's possibility that we cancellation request is sent but the backend query execution already errored out
in this PR we improve error message related to time out
only modify error message when the server error message indicated query cancellation happened, for other error messages unrelated to cancellation, we return directly
> SNOW-2007887: improve error message handling related to timeout

- src/snowflake/connector/network.py
- test/unit/test_network.py
Fixes SNOW-2027116
On the old driver CI, the restful interface failed when UUID objects are passed. Fix by using in `network.py::SnowflakeRestful` a customized JSON encoder (subclassed from Python) which adds support for Python UUID objects.
not applicable.
> SNOW-2027116 Allow for UUID encoding in SnowflakeRestful interface

- test/integ/test_cursor.py
Previous mock was being overwritten by new timebomb creation here:
https://github.com/snowflakedb/snowflake-connector-python/blob/6e214d01d18de7aae506063d0614f2b4b5148e41/src/snowflake/connector/cursor.py#L682
causing the test to fail from time to time.
> NO-SNOW Fix flaky query timeout test

- Jenkinsfile
> SNOW-2040000 change tag to bptp-stable

- src/snowflake/connector/wif_util.py
- test/unit/test_auth_workload_identity.py
This is a small follow-up to #2203 which populates the default Snowflake resource for Azure / Entra ID.
> Add default entra app ID for Snowflake

- src/snowflake/connector/wif_util.py
- test/unit/test_auth_workload_identity.py
This is a small follow-up to https://github.com/snowflakedb/snowflake-connector-python/pull/2203 which allows for both v1 and v2 formats of Entra ID issuers.
> Accept both v1 and v2 Entra ID issuer formats for WIF

- DESCRIPTION.md
- src/snowflake/connector/ocsp_snowflake.py
- test/integ/sso/test_unit_mfa_cache.py
- test/unit/test_ocsp.py
> SNOW-2048239 revert zero timeout for oscp cache lock

- src/snowflake/connector/auth/oauth_code.py
- src/snowflake/connector/connection.py
- test/unit/test_auth_oauth_auth_code.py
- test/unit/test_connection.py
A client can optionally include `enable_single_use_refresh_tokens=true` in the authorization code flow to opt-in to single-use refresh token semantics. This is part of a new security feature in Snowflake's native OAuth implementation.
To enable this, a user can set the `enable_single_use_refresh_tokens` connection parameter.
> Support client-side opt-in of Refresh Token Rotation in Snowflake OAuth

- DESCRIPTION.md
- setup.py
- src/snowflake/connector/arrow_context.py
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/CArrowChunkIterator.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.hpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/SnowflakeType.hpp
- test/integ/test_arrow_result.py
- test/unit/test_converter.py
Fixes SNOW-2052629
This PR adds basic support for INTERVAL YEAR MONTH and INTERVAL DAY TIME to the python connector.
Only supports arrow in this PR. Support for JSON will be added in a separate PR.
Implementation details:
- For year-month interval we receive number of months as integer from server. Python timedelta only supports days, seconds and microseconds so this simply mapped to int. In numpy it is mapped to numpy.timedelta64.
- For day-time interval we number of nanoseconds as integer (if precision <=5) …
> SNOW-2052629: Add basic arrow support for Interval data types

- src/snowflake/connector/bind_upload_agent.py
- src/snowflake/connector/cursor.py
- src/snowflake/connector/direct_file_operation_utils.py
- test/integ/test_direct_file_operation_utils.py
- test/unit/test_bind_upload_agent.py
- relax the condition of using stage solution for array bind (so we will use bind_size >= threshold instead of bind_size > threshold)
- use _upload_stream to implement BindUploadAgent
- the new test_direct_file_operation_utils.py to validate parse_file_operation for _upload and _upload_stream
- existing test test_bindings.py to make sure the change does not break existing bind upload logic
Fixes #NNNN
4. (Optional) PR for …
> SNOW-2057867 refactor BindUploadAgent to make it work for Python sprocs

- DESCRIPTION.md
- src/snowflake/connector/gcs_storage_client.py
- test/unit/test_gcs_client.py
Fixes SNOW-2100781
Fix missing parameter when calculating the endpoint in GCS storage client.
> SNOW-2100781: Fix use_virtual_url in GCS

- DESCRIPTION.md
- setup.cfg
Fixes #SNOW-2111939
Since cryptography v.45, some of the keys are not properly deserialized, causing the driver to fail.
> SNOW-2111939: Bind cryptography to latest known working version

- src/snowflake/connector/_aws_sign_v4.py
- test/unit/test_boto_compatibility.py
> SNOW-2183023: http session unmanaged requests

- test/unit/test_s3_redirect_403.py
> SNOW-2211783: detect in tests s3 redirects throwing 403

- DESCRIPTION.md
- src/snowflake/connector/arrow_context.py
- src/snowflake/connector/converter.py
- src/snowflake/connector/interval_util.py
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.cpp
- src/snowflake/connector/nanoarrow_cpp/ArrowIterator/IntervalConverter.hpp
- test/integ/test_arrow_result.py
- test/integ/test_interval_types.py
Fixes SNOW-2119489
This PR adds support for INTERVAL YEAR MONTH and INTERVAL DAY TIME to the python connector in JSON format.
Implementation details:
For year-month interval we receive number of months as integer (represented as string) from server. Python timedelta only supports days, seconds and microseconds so this is mapped to ANSI formatted interval string. In numpy it is mapped to numpy.timedelta64.
For day-time interval we receive number of nanoseconds as integer (represented as string). We convert …
> SNOW-2119489: Add support for interval types in json format

- DESCRIPTION.md
- src/snowflake/connector/auth/_oauth_base.py
- test/unit/test_auth_oauth_auth_code.py
- test/unit/test_oauth_token.py
Fixes #SNOW-2229745
Move `OAUTH_TYPE` into `CLIENT_ENVIRONMENT` for login requests.
> SNOW-2229745: Move oauth_type into client_environment

- src/snowflake/connector/wif_util.py
- test/csp_helpers.py
- test/unit/test_auth_workload_identity.py
Our [previous attempt](https://github.com/snowflakedb/snowflake-connector-python/pull/2367) to support AWS sovereign partitions parsed the partition out of the caller's ARN, which required a call to `get_caller_identity()` first. Unfortunately, in non-default partitions, a naive call to `session.client("sts").get_caller_identity()` will use STS in the default partition, rather than the current partition. The only way to fix this is to provide the partition, which would defeat the purpose.
Luckily, we can also extract the partition from the region, which we already have. The region's partition is guaranteed to match the identity's partition when running on AWS. boto provides a library function to extract the partition out of the region.
As a bonus, this removes one more API call from the …
> Fix bug in AWS sovereign partition support

- DESCRIPTION.md
- ci/build_windows.bat
- setup.cfg
> SNOW-2047992 Include VCRedist library into Windows wheels and get rid of PyArrow version constraint

- DESCRIPTION.md
- src/snowflake/connector/version.py
- tested_requirements/requirements_310.reqs
- tested_requirements/requirements_311.reqs
- tested_requirements/requirements_312.reqs
- tested_requirements/requirements_313.reqs
- tested_requirements/requirements_39.reqs
> SNOW-2274695 Bump up to 3.17.2 version

- DESCRIPTION.md
- src/snowflake/connector/config_manager.py
- test/unit/test_configmanager.py
Fixes #SNOW-216171 
The convention for the connections.toml file permissions is that if the file is writable by others, then an error should be raised. If the file is readable by others, a warning should be printed, with the possibility to skip the warning using an environment variable.
> SNOW-2161716: Fix config file permissions check and skip warning using env variable

- setup.cfg
Freeze `pytest-rerunfailures` dependency on last stable version
> Freeze pytest-rerunfailures

- test/integ/test_dbapi.py
Newest bptp-stable seem to change error sent as a response to invalid stored procedure call, yet it remains unchanged for prod. This PR adjusts test assertion
> Fix Jenkins build

- src/snowflake/connector/session_manager.py
- src/snowflake/connector/vendored/requests/__init__.py
- src/snowflake/connector/vendored/requests/adapters.py
- src/snowflake/connector/vendored/requests/compat.py
- src/snowflake/connector/vendored/requests/exceptions.py
- src/snowflake/connector/vendored/requests/help.py
- src/snowflake/connector/vendored/requests/models.py
- src/snowflake/connector/vendored/requests/utils.py
- src/snowflake/connector/vendored/urllib3/connection.py
- src/snowflake/connector/vendored/urllib3/contrib/emscripten/__init__.py
- test/unit/test_proxies.py
> SNOW-896926 adjust vendored urllib3 and requests

- DESCRIPTION.md
- src/snowflake/connector/auth/_auth.py
- test/unit/test_auth.py
Fixes #SNOW-2329031
During Oauth v2.0 implementation in #2135 introduced a breaking change(changing an exception type) for old authenticator. This PR reverts that to old behavior for backwards compatibility
> SNOW-2329031: revert exception type for Oauth authenticator

- DESCRIPTION.md
- src/snowflake/connector/connection.py
- src/snowflake/connector/cursor.py
- test/integ/test_async.py
- test/unit/test_cursor.py
Port PR: https://github.com/snowflakedb/Stored-Proc-Python-Connector/pull/225
On main, the following code shows the following mypy errors:
```
from snowflake.connector import connect, DictCursor
def main() -> None:
conn = connect()
c1 = conn.cursor()
print([row[0] for row in c1.fetchall()])
c2: DictCursor = conn.cursor(DictCursor)
print([row["COL1"] for row in c2.fetchall()])
```
- `error: Incompatible types in assignment (expression has type "SnowflakeCursor", variable has type "DictCursor")  [assignment]`
- `error: No overload variant of "__getitem__" of "tuple" matches argument type "str"  [call-overload]`
This change fixes both errors.
> SNOW-2333702 Fix types for DictCursor
